// Separate word list for Prüfung Training Quiz
// Structure: { [level]: { [chapter]: [ {question, answer}, ... ] } }
export const prufungWordList = {
  A1: {
    1: [
        { question: "die Woche", answer: "the week" },
        { question: "Montag", answer: "Monday" },
        { question: "Dienstag", answer: "Tuesday" },
        { question: "Mittwoch", answer: "Wednesday" },
        { question: "Donnerstag", answer: "Thursday" },
        { question: "Freitag", answer: "Friday" },
        { question: "Samstag", answer: "Saturday" },
        { question: "Sonntag", answer: "Sunday" },
        { question: "am + Tag", answer: "on + day (e.g., am Montag)" },
        { question: "am Montag", answer: "on Monday" },
        { question: "das Wochenende", answer: "the weekend" },
        { question: "am Wochenende", answer: "on the weekend" },
        { question: "der Feiertag", answer: "the public holiday" },
        { question: "das Jahr", answer: "the year" },
        { question: "der Monat", answer: "the month" },
        { question: "Januar", answer: "January" },
        { question: "Februar", answer: "February" },
        { question: "März", answer: "March" },
        { question: "April", answer: "April" },
        { question: "Mai", answer: "May" },
        { question: "Juni", answer: "June" },
        { question: "Juli", answer: "July" },
        { question: "August", answer: "August" },
        { question: "September", answer: "September" },
        { question: "Oktober", answer: "October" },
        { question: "November", answer: "November" },
        { question: "Dezember", answer: "December" },
        { question: "im + Monat", answer: "in + month (e.g., im Januar)" },
        { question: "im Januar", answer: "in January" },
        { question: "der Frühling", answer: "the spring" },
        { question: "der Sommer", answer: "the summer" },
        { question: "der Herbst", answer: "the autumn / the fall" },
        { question: "der Winter", answer: "the winter" },
        { question: "der Tag", answer: "the day" },
        { question: "der Morgen", answer: "the morning" },
        { question: "der Vormittag", answer: "the late morning" },
        { question: "der Mittag", answer: "the noon / the midday" },
        { question: "der Nachmittag", answer: "the afternoon" },
        { question: "der Abend", answer: "the evening" },
        { question: "die Nacht", answer: "the night" },
        { question: "am Morgen", answer: "in the morning" },
        { question: "am Vormittag", answer: "in the late morning" },
        { question: "am Mittag", answer: "at noon / at midday" },
        { question: "am Nachmittag", answer: "in the afternoon" },
        { question: "am Abend", answer: "in the evening" },
        { question: "in der Nacht", answer: "at night" },
        { question: "der erste August", answer: "the first of August" },
        { question: "am ersten August", answer: "on the first of August" },
        { question: "die Uhrzeit", answer: "the time (of day)" },
        { question: "Wann?", answer: "When?" },
        { question: "Wie spät ist es?", answer: "What time is it?" },
        { question: "Wie viel Uhr ist es?", answer: "What time is it? (How many o'clock is it?)" },
        { question: "Es ist ...", answer: "It is ..." },
        { question: "ein Uhr", answer: "one o'clock" },
        { question: "halb zwei", answer: "half past one (half to two)" },
        { question: "Viertel vor drei", answer: "quarter to three" },
        { question: "Viertel nach drei", answer: "quarter past three" },
        { question: "fünf (Minuten) vor vier", answer: "five minutes to four" },
        { question: "kurz vor 4", answer: "shortly before 4" },
        { question: "gleich 4", answer: "almost 4 / soon 4" },
        { question: "genau 4 Uhr", answer: "exactly 4 o'clock" },
        { question: "fünf (Minuten) nach 4", answer: "five (minutes) past 4" },
        { question: "Es ist vierzehn Uhr dreißig.", answer: "It is fourteen thirty (2:30 PM)." },
        { question: "= Es ist halb 3.", answer: "= It is half past two (literally: half to three)." },
        { question: "um 3 Uhr", answer: "at 3 o'clock" },
        { question: "von 2 bis 3 Uhr", answer: "from 2 to 3 o'clock" },
        { question: "ab 3 Uhr", answer: "starting from 3 o'clock" },
        { question: "anfangen", answer: "to begin / to start" },
        { question: "der Anfang", answer: "the beginning / the start" },
        { question: "aufhören", answer: "to stop / to end" },
        { question: "das Ende", answer: "the end" },
        { question: "dauern", answer: "to last / to take (time)" }
    ],
    2: [
        { question: "der Vorname", answer: "the first name" },
        { question: "der Nachname", answer: "the last name" },
        { question: "der Familienname", answer: "the family name" },
        { question: "heißen", answer: "to be called" },
        { question: "buchstabieren", answer: "to spell" },
        { question: "die Frau", answer: "the woman" },
        { question: "der Mann", answer: "the man" },
        { question: "die Dame", answer: "the lady" },
        { question: "der Herr", answer: "the gentleman" },
        { question: "männlich", answer: "male / masculine" },
        { question: "weiblich", answer: "female / feminine" },
        { question: "das Mädchen", answer: "the girl" },
        { question: "der Junge", answer: "the boy" },
        { question: "die Adresse", answer: "the address" },
        { question: "der Wohnort", answer: "the place of residence" },
        { question: "wohnen", answer: "to live / to reside" },
        { question: "leben", answer: "to live" },
        { question: "die Straße", answer: "the street" },
        { question: "der Platz", answer: "the place" },
        { question: "die Nummer", answer: "the number" },
        { question: "die Hausnummer", answer: "the house number" },
        { question: "die Stadt", answer: "the city" },
        { question: "die Postleitzahl", answer: "the postal code" },
        { question: "das Dorf", answer: "the village" },
        { question: "das Land", answer: "the country / the land" },
        { question: "das Telefon", answer: "the telephone" },
        { question: "telefonieren", answer: "to telephone / to make a call" },
        { question: "anrufen", answer: "to call (on the phone)" },
        { question: "die E-Mail", answer: "the email" },
        { question: "Ich bin geboren am ...", answer: "I was born on ..." },
        { question: "das Geburtsdatum", answer: "the date of birth" },
        { question: "der Geburtstag", answer: "the birthday" },
        { question: "geboren in", answer: "born in" },
        { question: "... Jahre alt sein", answer: "to be ... years old" },
        { question: "Robert ist 30 Jahre alt.", answer: "Robert is 30 years old." },
        { question: "die Familie", answer: "the family" },
        { question: "der Familienstand", answer: "the marital status" },
        { question: "verheiratet", answer: "married" },
        { question: "ledig", answer: "single / unmarried" },
        { question: "heiraten", answer: "to marry" },
        { question: "die Ehefrau", answer: "the wife" },
        { question: "der Ehemann", answer: "the husband" },
        { question: "die Hochzeit", answer: "the wedding" },
        { question: "der Vater", answer: "the father" },
        { question: "die Mutter", answer: "the mother" },
        { question: "die Eltern (Plural)", answer: "the parents" },
        { question: "das Kind", answer: "the child" },
        { question: "das Baby", answer: "the baby" },
        { question: "der Sohn", answer: "the son" },
        { question: "die Tochter", answer: "the daughter" },
        { question: "der Bruder", answer: "the brother" },
        { question: "die Schwester", answer: "the sister" },
        { question: "die Geschwister (Plural)", answer: "the siblings" },
        { question: "die Großmutter/Oma", answer: "the grandmother/grandma" },
        { question: "der Großvater/Opa", answer: "the grandfather/grandpa" },
        { question: "die Großeltern (Plural)", answer: "the grandparents" },
        { question: "die Verwandten (Plural)", answer: "the relatives" },
        { question: "der Freund", answer: "the friend (male)" },
        { question: "die Freundin", answer: "the friend (female)" },
        { question: "der/die Bekannte", answer: "the acquaintance (male/female)" },
        { question: "der/die Erwachsene", answer: "the adult (male/female)" },
        { question: "der Jugendliche", answer: "the youth (male)" },
        { question: "der Kindergarten", answer: "the preschool" },
        { question: "der Pass", answer: "the passport" },
        { question: "der Reisepass", answer: "the passport" },
        { question: "der Ausweis", answer: "the ID card / the identification" },
        { question: "die Papiere", answer: "the papers / the documents" },
        { question: "das Formular", answer: "the form" },
        { question: "ein Formular ausfüllen", answer: "to fill out a form" },
        { question: "die Staatsangehörigkeit", answer: "the citizenship / the nationality" },
        { question: "der Führerschein", answer: "the driver's license" },
        { question: "unterschreiben", answer: "to sign" },
        { question: "die Unterschrift", answer: "the signature" }
    ],
    3: [
    ],
    4: [
    ],
    5: [
    ],
    6: [
    ],
    7: [
    ],
    8: [
    ],
    9: [
    ],
    10: [
    ]
  },
  A2: {
    1: [
        { question: "der Tag", answer: "the day" },
        { question: "die Woche", answer: "the week" },
        { question: "das Wochenende", answer: "the weekend" },
        { question: "am Wochenende", answer: "on the weekend" },
        { question: "der Feiertag", answer: "the holiday" },
        { question: "das Jahr", answer: "the year" },
        { question: "der Monat", answer: "the month" },
        { question: "am + Tag", answer: "on + day" },
        { question: "am Montag", answer: "on Monday" },
        { question: "im + Monat", answer: "in + month" },
        { question: "im Januar", answer: "in January" },
        { question: "der Frühling", answer: "the spring" },
        { question: "der Sommer", answer: "the summer" },
        { question: "der Herbst", answer: "the autumn / fall" },
        { question: "der Winter", answer: "the winter" },
        { question: "der Morgen", answer: "the morning" },
        { question: "der Vormittag", answer: "the after morning and before noon" },
        { question: "der Mittag", answer: "the noon / midday" },
        { question: "der Nachmittag", answer: "the afternoon" },
        { question: "der Abend", answer: "the evening" },
        { question: "die Nacht", answer: "the night" },
        { question: "am Morgen/Vormittag", answer: "in the morning / forenoon" },
        { question: "am Mittag", answer: "at noon" },
        { question: "am Nachmittag", answer: "in the afternoon" },
        { question: "am Abend", answer: "in the evening" },
        { question: "in der Nacht", answer: "at night" },
        { question: "morgens", answer: "in the mornings" },
        { question: "vormittags", answer: "in the late mornings" },
        { question: "mittags", answer: "at noons" },
        { question: "nachmittags", answer: "in the afternoons" },
        { question: "abends", answer: "in the evenings" },
        { question: "nachts", answer: "at nights" },
        { question: "täglich", answer: "daily" },
        { question: "immer", answer: "always" },
        { question: "meistens", answer: "mostly / usually" },
        { question: "oft", answer: "often" },
        { question: "manchmal", answer: "sometimes" },
        { question: "nie", answer: "never" },
        { question: "bald", answer: "soon" },
        { question: "gleich", answer: "immediately / in a moment" },
        { question: "sofort", answer: "immediately / right away" },
        { question: "später", answer: "later" },
        { question: "vorgestern", answer: "the day before yesterday" },
        { question: "gestern", answer: "yesterday" },
        { question: "heute", answer: "today" },
        { question: "morgen", answer: "tomorrow" },
        { question: "übermorgen", answer: "day after tomorrow" },
        { question: "das Datum", answer: "the date" },
        { question: "der erste August", answer: "the first of August" },
        { question: "am ersten August", answer: "on the first of August" },
        { question: "die Uhrzeit", answer: "the time (of day)" },
        { question: "Wann?", answer: "When?" },
        { question: "Wie spät ist es?", answer: "What time is it?" },
        { question: "Wie viel Uhr ist es?", answer: "What time is it?" },
        { question: "Es ist ...", answer: "It is ..." },
        { question: "ein Uhr.", answer: "one o'clock." },
        { question: "halb zwei.", answer: "half past one (literally: half to two)." },
        { question: "Viertel vor drei.", answer: "quarter to three." },
        { question: "Viertel nach drei.", answer: "quarter past three." },
        { question: "fünf (Minuten) vor vier.", answer: "five (minutes) to four." },
        { question: "kurz vor vier.", answer: "shortly before four." },
        { question: "gleich vier.", answer: "almost four / soon four." },
        { question: "genau vier Uhr.", answer: "exactly four o'clock." },
        { question: "fünf (Minuten) nach vier.", answer: "five (minutes) past four." },
        { question: "Es ist vierzehn Uhr dreißig.", answer: "It is fourteen thirty (2:30 PM)." },
        { question: "= Es ist halb drei.", answer: "= It is half past two (literally: half to three)." },
        { question: "um drei Uhr", answer: "at three o'clock" },
        { question: "von zwei bis drei Uhr", answer: "from two to three o'clock" },
        { question: "ab drei Uhr", answer: "starting from three o'clock" },
        { question: "anfangen", answer: "to begin / to start" },
        { question: "der Anfang", answer: "the beginning" },
        { question: "aufhören", answer: "to stop" },
        { question: "das Ende", answer: "the end" },
        { question: "dauern", answer: "to last / to take (time)" },
        { question: "der Termin", answer: "the appointment / the date (for an event)" },
        { question: "einen Termin vereinbaren/ausmachen", answer: "to arrange an appointment / to make an appointment" },
        { question: "einen Termin verschieben", answer: "to postpone an appointment / to reschedule an appointment" },
        { question: "verabredet sein", answer: "to have an arrangement (usually social) / to be meeting (someone)" }
    ],
    2: [
        { question: "der Vorname", answer: "the first name" },
        { question: "der Nachname", answer: "the last name" },
        { question: "der Familienname", answer: "the family name" },
        { question: "heißen", answer: "to be called" },
        { question: "buchstabieren", answer: "to spell" },
        { question: "die Frau", answer: "the woman" },
        { question: "der Mann", answer: "the man" },
        { question: "männlich", answer: "male / masculine" },
        { question: "weiblich", answer: "female / feminine" },
        { question: "Frau + Nachname", answer: "Mrs. / Ms. + last name" },
        { question: "Herr + Nachname", answer: "Mr. + last name" },
        { question: "der Junge", answer: "the boy" },
        { question: "das Mädchen", answer: "the girl" },
        { question: "die Adresse", answer: "the address" },
        { question: "der Wohnort", answer: "the place of residence " },
        { question: "wohnen", answer: "to live/to reside" },
        { question: "leben", answer: "to live" },
        { question: "die Straße", answer: "the street" },
        { question: "der Platz", answer: "the place" },
        { question: "die Hausnummer", answer: "the house number" },
        { question: "die Postleitzahl", answer: "the postal code" },
        { question: "die Stadt", answer: "the city" },
        { question: "das Dorf", answer: "the village" },
        { question: "das Land", answer: "the country" },
        { question: "das Telefon", answer: "the telephone" },
        { question: "telefonieren", answer: "to make a call" },
        { question: "anrufen", answer: "to call" },
        { question: "die Telefonnummer", answer: "the telephone number" },
        { question: "die Vorwahl", answer: "the area code / the dialing code" },
        { question: "erreichen", answer: "to reach" },
        { question: "die E-Mail-Adresse", answer: "the email address" },
        { question: "per E-Mail", answer: "by email" },
        { question: "ich bin geboren am", answer: "I was born on" },
        { question: "das Geburtsdatum", answer: "the date of birth" },
        { question: "der Geburtstag", answer: "the birthday" },
        { question: "geboren in", answer: "born in" },
        { question: "der Geburtsort", answer: "the place of birth" },
        { question: "Robert ist 30 Jahre alt.", answer: "Robert is 30 years old." },
        { question: "die Familie", answer: "the family" },
        { question: "der Familienstand", answer: "the marital status" },
        { question: "ledig", answer: "single / unmarried" },
        { question: "verheiratet", answer: "married" },
        { question: "heiraten", answer: "to marry" },
        { question: "getrennt leben", answer: "to live separately" },
        { question: "geschieden sein", answer: "to be divorced" },
        { question: "die Ehefrau", answer: "the wife" },
        { question: "der Ehemann", answer: "the husband" },
        { question: "die Hochzeit", answer: "the wedding" },
        { question: "der Vater", answer: "the father" },
        { question: "die Mutter", answer: "the mother" },
        { question: "die Eltern (Plural)", answer: "the parents" },
        { question: "das Kind", answer: "the child" },
        { question: "das Baby", answer: "the baby" },
        { question: "der Sohn", answer: "the son" },
        { question: "die Tochter", answer: "the daughter" },
        { question: "der Bruder", answer: "the brother" },
        { question: "die Schwester", answer: "the sister" },
        { question: "die Geschwister (Plural)", answer: "the siblings" },
        { question: "die Großmutter/Oma", answer: "the grandmother/grandma" },
        { question: "der Großvater/Opa", answer: "the grandfather/grandpa" },
        { question: "die Großeltern (Plural)", answer: "the grandparents" },
        { question: "der Freund", answer: "the friend (male) / the boyfriend" },
        { question: "die Freundin", answer: "the friend (female) / the girlfriend" },
        { question: "der/die Bekannte", answer: "the acquaintance (male/female)" },
        { question: "der/die Erwachsene", answer: "the adult (male/female)" },
        { question: "der/die Jugendliche", answer: "the youth (male/female)" },
        { question: "der Kindergarten", answer: "the kindergarden / the preschool" },
        { question: "der Pass/Reisepass", answer: "the passport" },
        { question: "der Ausweis", answer: "the ID card / the identification" },
        { question: "die Papiere (Plural)", answer: "the papers / the documents" },
        { question: "das Formular", answer: "the form" },
        { question: "ein Formular ausfüllen", answer: "to fill out a form" },
        { question: "die Staatsangehörigkeit/Nationalität", answer: "the citizenship / the nationality" },
        { question: "der Führerschein", answer: "the driver's license" },
        { question: "unterschreiben", answer: "to sign" },
        { question: "die Unterschrift", answer: "the signature" }
    ],
    3: [
        { question: "wohnen", answer: "to live" },
        { question: "die Wohnung", answer: "the apartment / the flat" },
        { question: "das Haus", answer: "the house" },
        { question: "das Zimmer", answer: "the room" },
        { question: "der Raum", answer: "the room" },
        { question: "das Wohnzimmer", answer: "the living room" },
        { question: "das Schlafzimmer", answer: "the bedroom" },
        { question: "das Kinderzimmer", answer: "the children's room" },
        { question: "die Küche", answer: "the kitchen" },
        { question: "das Badezimmer / das Bad", answer: "the bathroom" },
        { question: "die Toilette / das WC", answer: "the toilet" },
        { question: "der Quadratmeter", answer: "the square meter" },
        { question: "der Stock", answer: "the floor (of a building)" },
        { question: "im ersten Stock wohnen", answer: "to live on the first floor" },
        { question: "die Miete", answer: "the rent" },
        { question: "der/die Mieter/in", answer: "the tenant (male/female)" },
        { question: "der/die Vermieter/in", answer: "the landlord/landlady" },
        { question: "mieten", answer: "to rent" },
        { question: "vermieten", answer: "to rent out / to let" },
        { question: "einziehen", answer: "to move in" },
        { question: "ausziehen", answer: "to move out / to take off (clothes)" },
        { question: "umziehen", answer: "to move (residence) / to change clothes" },
        { question: "die Tür", answer: "the door" },
        { question: "das Fenster", answer: "the window" },
        { question: "der Eingang", answer: "the entrance" },
        { question: "der Ausgang", answer: "the exit" },
        { question: "der Balkon", answer: "the balcony" },
        { question: "der Garten", answer: "the garden" },
        { question: "die Garage", answer: "the garage" },
        { question: "der Keller", answer: "the basement" },
        { question: "das Dach", answer: "the roof" },
        { question: "der Flur", answer: "the hallway / the corridor" },
        { question: "der Briefkasten", answer: "the mailbox / the letterbox" },
        { question: "der Müll", answer: "the garbage" },
        { question: "die Möbel (Plural)", answer: "the furniture" },
        { question: "der Tisch", answer: "the table" },
        { question: "der Stuhl", answer: "the chair" },
        { question: "der Sessel", answer: "the armchair" },
        { question: "der Schrank", answer: "the cupboard / the closet / the wardrobe" },
        { question: "der Teppich", answer: "the carpet" },
        { question: "das Bett", answer: "the bed" },
        { question: "der Herd", answer: "the stove" },
        { question: "der Kühlschrank", answer: "the refrigerator" },
        { question: "die Heizung", answer: "the heating" },
        { question: "die Dusche", answer: "the shower" },
        { question: "das Handtuch", answer: "the towel" },
        { question: "der Spiegel", answer: "the mirror" },
        { question: "das Bild", answer: "the picture / the painting" },
        { question: "die Uhr", answer: "the clock / the watch / the hour" },
        { question: "das Licht", answer: "the light" },
        { question: "das Licht anmachen", answer: "to turn on the light" },
        { question: "das Licht ausmachen", answer: "to turn off the light" },
        { question: "der Aufzug", answer: "the elevator / the lift" },
        { question: "die Treppe", answer: "the stairs" },
        { question: "der Schlüssel", answer: "the key" },
        { question: "das Geschirr", answer: "the dishes" },
        { question: "das Besteck", answer: "the cutlery" },
        { question: "der Löffel", answer: "the spoon" },
        { question: "das Messer", answer: "the knife" },
        { question: "die Gabel", answer: "the fork" },
        { question: "der Teller", answer: "the plate" },
        { question: "der Mietvertrag", answer: "the rental agreement / the lease" },
        { question: "unterschreiben", answer: "to sign" },
        { question: "auspacken", answer: "to unpack" },
        { question: "aufräumen", answer: "to tidy up / to clean up" },
        { question: "renovieren", answer: "to renovate" },
        { question: "reparieren", answer: "to repair" },
        { question: "schmutzig", answer: "dirty" },
        { question: "sauber", answer: "clean" },
        { question: "putzen", answer: "to clean / to polish" }
    ],
    4: [
        { question: "der Weg", answer: "the way / the path / the road" },
        { question: "jemanden nach dem Weg fragen", answer: "to ask someone for directions" },
        { question: "jemandem den Weg zeigen", answer: "to show someone the way / to give someone directions" },
        { question: "geradeaus", answer: "straight ahead" },
        { question: "links", answer: "left" },
        { question: "rechts", answer: "right" },
        { question: "weit", answer: "far" },
        { question: "in der Nähe (von)", answer: "near (to)" },
        { question: "das Auto", answer: "the car" },
        { question: "der LKW (Lastkraftwagen)", answer: "the truck" },
        { question: "der Bus", answer: "the bus" },
        { question: "das Fahrrad", answer: "the bicycle / the bike" },
        { question: "der Zug", answer: "the train" },
        { question: "die Straßenbahn", answer: "the tram" },
        { question: "die U-Bahn", answer: "the underground (metro)" },
        { question: "die S-Bahn", answer: "the S-Bahn (city train)" },
        { question: "das Taxi", answer: "the taxi" },
        { question: "das Schiff", answer: "the ship" },
        { question: "der Motorroller", answer: "the scooter" },
        { question: "mit dem Auto / mit dem Bus / mit dem Zug ... fahren", answer: "to travel/go by car / by bus / by train ..." },
        { question: "mit dem Rad/Fahrrad fahren", answer: "to cycle / to ride a bike" },
        { question: "parken", answer: "to park" },
        { question: "halten", answer: "to stop / to hold" },
        { question: "bremsen", answer: "to brake" },
        { question: "Stopp!", answer: "Stop!" },
        { question: "die Autobahn", answer: "the highway" },
        { question: "die Kreuzung", answer: "the crossing" },
        { question: "die Ecke", answer: "the corner" },
        { question: "der Unfall", answer: "the accident" },
        { question: "das Verkehrsschild", answer: "the traffic sign" },
        { question: "die Ampel", answer: "the traffic light" },
        { question: "die Baustelle", answer: "the construction site / the roadworks" },
        { question: "vorsichtig fahren", answer: "to drive carefully" },
        { question: "der Parkplatz", answer: "the parking lot" },
        { question: "der Reifen", answer: "the tire" },
        { question: "die Polizei rufen", answer: "to call the police" },
        { question: "der Führerschein", answer: "the driver's license" },
        { question: "das Flugzeug", answer: "the airplane" },
        { question: "fliegen (mit)", answer: "to fly (with)" },
        { question: "der Flughafen", answer: "the airport" },
        { question: "der Bahnhof", answer: "the train station" },
        { question: "die Durchsage", answer: "the announcement" },
        { question: "die Haltestelle", answer: "the bus stop / the station (for tram/U-Bahn etc.)" },
        { question: "die (U-Bahn-/S-Bahn-/Bus-) Linie", answer: "the (underground train/city train/bus) line" },
        { question: "abfahren", answer: "to depart / to leave" },
        { question: "die Abfahrt", answer: "the departure" },
        { question: "abfliegen", answer: "to fly off / to take off (by plane)" },
        { question: "der Abflug", answer: "the departure (by plane)" },
        { question: "ankommen", answer: "to arrive" },
        { question: "die Ankunft", answer: "the arrival" },
        { question: "die Fahrt", answer: "the trip / the journey / the ride" },
        { question: "von ... nach ...", answer: "from ... to ..." },
        { question: "dauern", answer: "to last / to take (time)" },
        { question: "einsteigen", answer: "to get in / to board" },
        { question: "aussteigen", answer: "to get out (from a vehicle)" },
        { question: "umsteigen", answer: "to change / to transfer" },
        { question: "die Fahrkarte", answer: "the ticket (for travel)" },
        { question: "das Ticket", answer: "the ticket" },
        { question: "hin und zurück", answer: "return (ticket) / there and back" },
        { question: "der Platz", answer: "the seat / the place" },
        { question: "reservieren", answer: "to reserve / to book" },
        { question: "die Reservierung", answer: "the reservation / the booking" },
        { question: "erste/zweite Klasse", answer: "first/second class" },
        { question: "die Ermäßigung", answer: "the discount / the reduction" },
        { question: "die Verspätung", answer: "the delay" },
        { question: "den Zug verpassen", answer: "to miss the train" },
        { question: "der Fahrplan", answer: "the timetable / the schedule" },
        { question: "das Gleis", answer: "the track / the platform (railway)" },
        { question: "das Gepäck", answer: "the luggage / the baggage" },
        { question: "der Koffer", answer: "the suitcase" },
        { question: "die Tasche", answer: "the bag" },
        { question: "die Reisetasche", answer: "the travel bag" },
        { question: "der Urlaub", answer: "the vacation / the holiday" },
        { question: "die Ferien (Plural)", answer: "the holidays" },
        { question: "Urlaub/Ferien machen", answer: "to take a vacation/holiday" },
        { question: "frei haben", answer: "to have time off / to be free" },
        { question: "die Reise", answer: "the journey / the trip" },
        { question: "reisen", answer: "to travel" },
        { question: "der Berg", answer: "the mountain" },
        { question: "der Strand", answer: "the beach" },
        { question: "das Meer / die See", answer: "the sea / the ocean" },
        { question: "der See", answer: "the lake" },
        { question: "der Wald", answer: "the forest" },
        { question: "der/die Tourist/in", answer: "the tourist (male/female)" },
        { question: "die Information", answer: "the information / the information desk" },
        { question: "das Reisebüro", answer: "the travel agency" },
        { question: "der/die Reiseführer/in", answer: "the tour guide (male/female) / the travel guide (book)" },
        { question: "der Ausflug", answer: "the outing / the trip" },
        { question: "der Spaziergang", answer: "the walk" },
        { question: "besichtigen", answer: "to visit / to sightsee" },
        { question: "besuchen", answer: "to visit (a person or place)" },
        { question: "das Hotel", answer: "the hotel" },
        { question: "die Pension", answer: "the guesthouse" },
        { question: "die Jugendherberge", answer: "the youth hostel" },
        { question: "die Rezeption", answer: "the reception (desk)" },
        { question: "der Gast", answer: "the guest" },
        { question: "das Formular", answer: "the form" },
        { question: "ein Formular ausfüllen", answer: "to fill out a form" },
        { question: "der Schlüssel", answer: "the key" },
        { question: "das Zimmer", answer: "the room" },
        { question: "das Einzelzimmer", answer: "the single room" },
        { question: "das Doppelzimmer", answer: "the double room" },
        { question: "mit/ohne Dusche/Bad", answer: "with/without shower/bath" },
        { question: "mit/ohne Frühstück", answer: "with/without breakfast" },
        { question: "die Stadtrundfahrt", answer: "the city tour" },
        { question: "die Ausstellung", answer: "the exhibition / the show" },
        { question: "die Sehenswürdigkeiten (Plural)", answer: "the landmarks" },
        { question: "Schöne Ferien!", answer: "Have a nice holiday!" },
        { question: "Gute Reise!", answer: "Have a good trip!" },
        { question: "machen", answer: "to make / to do" },
        { question: "trinken", answer: "to drink" },
        { question: "wohnen", answer: "to live (reside)" },
        { question: "schlafen", answer: "to sleep" },
        { question: "bleiben", answer: "to stay / to remain" },
        { question: "aufstehen", answer: "to get up" },
        { question: "gefallen", answer: "to please / to like (impersonal)" },
        { question: "fahren", answer: "to drive / to go (by vehicle)" },
        { question: "sehen", answer: "to see / to look" },
        { question: "kaufen", answer: "to buy" },
        { question: "besuchen", answer: "to visit" },
        { question: "mitbringen", answer: "to bring (along)" },
        { question: "kennenlernen", answer: "to get to know / to meet (for the first time)" },
        { question: "essen", answer: "to eat" },
        { question: "kommen", answer: "to come" },
        { question: "arbeiten", answer: "to work" }
    ],
    5: [
    ],
    6: [
    ],
    7: [
    ],
    8: [
    ],
    9: [
    ],
    10: [
    ],
    11: [
    ],
    12: [
    ]
  },
  B1: {
    1: [
        { question: "die Erfahrung", answer: "the experience" },
        { question: "die Möglichkeit", answer: "the possibility" },
        { question: "die Entscheidung", answer: "the decision" },
        { question: "die Verantwortung", answer: "the responsibility" },
        { question: "die Entwicklung", answer: "the development" }
    ],
    3: [
    ],
    4: [
    ],
    5: [
    ],
    6: [
    ],
    7: [
    ],
    8: [
    ],
    9: [
    ],
    10: [
    ],
    11: [
    ],
    12: [
    ]
  }
};
