export const verbs = [
  {en: "to be", pr: "sein", pe: "ist gewesen"},
  {en: "to have", pr: "haben", pe: "hat gehabt"},
  {en: "to go", pr: "gehen", pe: "ist gegangen"},
  {en: "to come", pr: "kommen", pe: "ist gekommen"},
  {en: "to do", pr: "machen", pe: "hat gemacht"},
  {en: "to say", pr: "sagen", pe: "hat gesagt"},
  {en: "to see", pr: "sehen", pe: "hat gesehen"},
  {en: "to eat", pr: "essen", pe: "hat gegessen"},
  {en: "to drink", pr: "trinken", pe: "hat getrunken"},
  {en: "to sleep", pr: "schlafen", pe: "hat geschlafen"},
  {en: "to learn", pr: "lernen", pe: "hat gelernt"},
  {en: "to study", pr: "studieren", pe: "hat studiert"},
  {en: "to work", pr: "arbeiten", pe: "hat gearbeitet"},
  {en: "to live", pr: "leben", pe: "hat gelebt"},
  {en: "to stay", pr: "bleiben", pe: "ist geblieben"},
  {en: "to find", pr: "finden", pe: "hat gefunden"},
  {en: "to give", pr: "geben", pe: "hat gegeben"},
  {en: "to take", pr: "nehmen", pe: "hat genommen"},
  {en: "to buy", pr: "kaufen", pe: "hat gekauft"},
  {en: "to sell", pr: "verkaufen", pe: "hat verkauft"},
  {en: "to need", pr: "brauchen", pe: "hat gebraucht"},
  {en: "to want", pr: "wollen", pe: "hat gewollt"},
  {en: "to can (be able to)", pr: "können", pe: "hat gekonnt"},
  {en: "to must (have to)", pr: "müssen", pe: "hat gemusst"},
  {en: "to should", pr: "sollen", pe: "hat gesollt"},
  {en: "to may (be allowed)", pr: "dürfen", pe: "hat gedurft"},
  {en: "to like", pr: "mögen", pe: "hat gemocht"},
  {en: "to know (a fact)", pr: "wissen", pe: "hat gewusst"},
  {en: "to know (a person/place)", pr: "kennen", pe: "hat gekannt"},
  {en: "to play", pr: "spielen", pe: "hat gespielt"},
  {en: "to read", pr: "lesen", pe: "hat gelesen"},
  {en: "to write", pr: "schreiben", pe: "hat geschrieben"},
  {en: "to speak", pr: "sprechen", pe: "hat gesprochen"},
  {en: "to hear", pr: "hören", pe: "hat gehört"},
  {en: "to wait", pr: "warten", pe: "hat gewartet"},
  {en: "to help", pr: "helfen", pe: "hat geholfen"},
  {en: "to think", pr: "denken", pe: "hat gedacht"},
  {en: "to believe", pr: "glauben", pe: "hat geglaubt"},
  {en: "to bring", pr: "bringen", pe: "hat gebracht"},
  {en: "to drive", pr: "fahren", pe: "ist gefahren"},
  {en: "to fly", pr: "fliegen", pe: "ist geflogen"},
  {en: "to run", pr: "laufen", pe: "ist gelaufen"},
  {en: "to walk", pr: "gehen", pe: "ist gegangen"},
  {en: "to open", pr: "öffnen", pe: "hat geöffnet"},
  {en: "to close", pr: "schließen", pe: "hat geschlossen"},
  {en: "to sit", pr: "sitzen", pe: "hat gesessen"},
  {en: "to stand", pr: "stehen", pe: "hat gestanden"},
  {en: "to lie (be lying)", pr: "liegen", pe: "hat gelegen"},
  {en: "to put", pr: "stellen", pe: "hat gestellt"},
  {en: "to lay (put down)", pr: "legen", pe: "hat gelegt"},
  {en: "to hang", pr: "hängen", pe: "hat gehängt"},
  {en: "to start", pr: "anfangen", pe: "hat angefangen"},
  {en: "to stop", pr: "aufhören", pe: "hat aufgehört"},
  {en: "to begin", pr: "beginnen", pe: "hat begonnen"},
  {en: "to end", pr: "enden", pe: "hat geendet"},
  {en: "to ask", pr: "fragen", pe: "hat gefragt"},
  {en: "to answer", pr: "antworten", pe: "hat geantwortet"},
  {en: "to call", pr: "rufen", pe: "hat gerufen"},
  {en: "to phone", pr: "anrufen", pe: "hat angerufen"},
  {en: "to meet", pr: "treffen", pe: "hat getroffen"},
  {en: "to visit", pr: "besuchen", pe: "hat besucht"},
  {en: "to invite", pr: "einladen", pe: "hat eingeladen"},
  {en: "to celebrate", pr: "feiern", pe: "hat gefeiert"},
  {en: "to cook", pr: "kochen", pe: "hat gekocht"},
  {en: "to bake", pr: "backen", pe: "hat gebacken"},
  {en: "to clean", pr: "putzen", pe: "hat geputzt"},
  {en: "to wash", pr: "waschen", pe: "hat gewaschen"},
  {en: "to shower", pr: "duschen", pe: "hat geduscht"},
  {en: "to get up", pr: "aufstehen", pe: "ist aufgestanden"},
  {en: "to go to bed", pr: "ins Bett gehen", pe: "ist ins Bett gegangen"},
  {en: "to dress", pr: "sich anziehen", pe: "hat sich angezogen"},
  {en: "to undress", pr: "sich ausziehen", pe: "hat sich ausgezogen"},
  {en: "to brush teeth", pr: "Zähne putzen", pe: "hat Zähne geputzt"},
  {en: "to laugh", pr: "lachen", pe: "hat gelacht"},
  {en: "to cry", pr: "weinen", pe: "hat geweint"},
  {en: "to smile", pr: "lächeln", pe: "hat gelächelt"},
  {en: "to wait for", pr: "warten auf", pe: "hat auf ... gewartet"},
  {en: "to explain", pr: "erklären", pe: "hat erklärt"},
  {en: "to describe", pr: "beschreiben", pe: "hat beschrieben"},
  {en: "to repeat", pr: "wiederholen", pe: "hat wiederholt"},
  {en: "to show", pr: "zeigen", pe: "hat gezeigt"},
  {en: "to look for", pr: "suchen", pe: "hat gesucht"},
  {en: "to find out", pr: "herausfinden", pe: "hat herausgefunden"},
  {en: "to forget", pr: "vergessen", pe: "hat vergessen"},
  {en: "to remember", pr: "sich erinnern", pe: "hat sich erinnert"},
  {en: "to begin", pr: "anfangen", pe: "hat angefangen"},
  {en: "to finish", pr: "fertig sein", pe: "ist fertig gewesen"},
  {en: "to stay", pr: "bleiben", pe: "ist geblieben"},
  {en: "to move", pr: "umziehen", pe: "ist umgezogen"},
  {en: "to travel", pr: "reisen", pe: "ist gereist"},
  {en: "to arrive", pr: "ankommen", pe: "ist angekommen"},
  {en: "to leave", pr: "verlassen", pe: "hat verlassen"},
  {en: "to get", pr: "bekommen", pe: "hat bekommen"},
  {en: "to pay", pr: "bezahlen", pe: "hat bezahlt"},
  {en: "to cost", pr: "kosten", pe: "hat gekostet"},
  {en: "to send", pr: "schicken", pe: "hat geschickt"},
  {en: "to receive", pr: "bekommen", pe: "hat bekommen"},
  {en: "to use", pr: "benutzen", pe: "hat benutzt"},
  {en: "to try", pr: "probieren", pe: "hat probiert"},
  {en: "to test", pr: "testen", pe: "hat getestet"},
  {en: "to plan", pr: "planen", pe: "hat geplant"},
  {en: "to prepare", pr: "vorbereiten", pe: "hat vorbereitet"},
  {en: "to begin", pr: "beginnen", pe: "hat begonnen"},
  {en: "to end", pr: "enden", pe: "hat geendet"},
  {en: "to clean up", pr: "aufräumen", pe: "hat aufgeräumt"},
  {en: "to repair", pr: "reparieren", pe: "hat repariert"},
  {en: "to cut", pr: "schneiden", pe: "hat geschnitten"},
  {en: "to build", pr: "bauen", pe: "hat gebaut"},
  {en: "to send", pr: "senden", pe: "hat gesendet"},
  {en: "to receive", pr: "empfangen", pe: "hat empfangen"},
  {en: "to stand up", pr: "aufstehen", pe: "ist aufgestanden"},
  {en: "to fall", pr: "fallen", pe: "ist gefallen"},
  {en: "to swim", pr: "schwimmen", pe: "ist geschwommen"},
  {en: "to climb", pr: "steigen", pe: "ist gestiegen"},
  {en: "to happen", pr: "passieren", pe: "ist passiert"},
  {en: "to change", pr: "ändern", pe: "hat geändert"},
  {en: "to wait", pr: "warten", pe: "hat gewartet"},
  {en: "to hope", pr: "hoffen", pe: "hat gehofft"},
  {en: "to explain", pr: "erklären", pe: "hat erklärt"},
  {en: "to mean", pr: "meinen", pe: "hat gemeint"},
  {en: "to show", pr: "zeigen", pe: "hat gezeigt"},
  {en: "to check", pr: "prüfen", pe: "hat geprüft"},
  {en: "to count", pr: "zählen", pe: "hat gezählt"},
  {en: "to happen", pr: "geschehen", pe: "ist geschehen"},
  {en: "to wait", pr: "warten", pe: "hat gewartet"},
  {en: "to stand up", pr: "aufstehen", pe: "ist aufgestanden"},
  {en: "to fall asleep", pr: "einschlafen", pe: "ist eingeschlafen"},
  {en: "to wake up", pr: "aufwachen", pe: "ist aufgewacht"},
  {en: "to bring along", pr: "mitbringen", pe: "hat mitgebracht"},
  {en: "to take along", pr: "mitnehmen", pe: "hat mitgenommen"},
  {en: "to think about", pr: "nachdenken", pe: "hat nachgedacht"},
  {en: "to participate", pr: "teilnehmen", pe: "hat teilgenommen"},
  {en: "to invite", pr: "einladen", pe: "hat eingeladen"},
  {en: "to call back", pr: "zurückrufen", pe: "hat zurückgerufen"},
  {en: "to write down", pr: "aufschreiben", pe: "hat aufgeschrieben"},
  {en: "to read aloud", pr: "vorlesen", pe: "hat vorgelesen"},
  {en: "to watch TV", pr: "fernsehen", pe: "hat ferngesehen"},
  {en: "to go out", pr: "ausgehen", pe: "ist ausgegangen"},
  {en: "to come back", pr: "zurückkommen", pe: "ist zurückgekommen"},
  {en: "to enter", pr: "eintreten", pe: "ist eingetreten"},
  {en: "to leave", pr: "weggehen", pe: "ist weggegangen"},
  {en: "to put on", pr: "anziehen", pe: "hat angezogen"},
  {en: "to take off", pr: "ausziehen", pe: "hat ausgezogen"},
  {en: "to pick up", pr: "abholen", pe: "hat abgeholt"},
  {en: "to clean up", pr: "aufräumen", pe: "hat aufgeräumt"},
  {en: "to switch on", pr: "einschalten", pe: "hat eingeschaltet"},
  {en: "to switch off", pr: "ausschalten", pe: "hat ausgeschaltet"},
  {en: "to fill", pr: "füllen", pe: "hat gefüllt"},
  {en: "to learn", pr: "lernen", pe: "hat gelernt"},
  {en: "to teach", pr: "unterrichten", pe: "hat unterrichtet"},
  {en: "to play", pr: "spielen", pe: "hat gespielt"},
  {en: "to swim", pr: "schwimmen", pe: "ist geschwommen"},
  {en: "to jump", pr: "springen", pe: "ist gesprungen"},
  {en: "to draw", pr: "zeichnen", pe: "hat gezeichnet"},
  {en: "to paint", pr: "malen", pe: "hat gemalt"},
  {en: "to laugh", pr: "lachen", pe: "hat gelacht"},
  {en: "to cry", pr: "weinen", pe: "hat geweint"},
  {en: "to hope", pr: "hoffen", pe: "hat gehofft"},
  {en: "to love", pr: "lieben", pe: "hat geliebt"},
  {en: "to hate", pr: "hassen", pe: "hat gehasst"},
  {en: "to wait", pr: "warten", pe: "hat gewartet"},
  {en: "to explain", pr: "erklären", pe: "hat erklärt"},
  {en: "to remember", pr: "sich erinnern", pe: "hat sich erinnert"},
  {en: "to forget", pr: "vergessen", pe: "hat vergessen"},
  {en: "to miss", pr: "verpassen", pe: "hat verpasst"},
  {en: "to open", pr: "öffnen", pe: "hat geöffnet"},
  {en: "to close", pr: "schließen", pe: "hat geschlossen"},
  {en: "to stay overnight", pr: "übernachten", pe: "hat übernachtet"},
  {en: "to visit", pr: "besuchen", pe: "hat besucht"},
  {en: "to organize", pr: "organisieren", pe: "hat organisiert"},
  {en: "to order", pr: "bestellen", pe: "hat bestellt"},
  {en: "to reserve", pr: "reservieren", pe: "hat reserviert"},
  {en: "to search", pr: "suchen", pe: "hat gesucht"},
  {en: "to find", pr: "finden", pe: "hat gefunden"},
  {en: "to help", pr: "helfen", pe: "hat geholfen"},
  {en: "to stay", pr: "bleiben", pe: "ist geblieben"},
  {en: "to work", pr: "arbeiten", pe: "hat gearbeitet"},
  {en: "to relax", pr: "sich entspannen", pe: "hat sich entspannt"},
  {en: "to rest", pr: "sich ausruhen", pe: "hat sich ausgeruht"},
  {en: "to move house", pr: "umziehen", pe: "ist umgezogen"},
  {en: "to get up", pr: "aufstehen", pe: "ist aufgestanden"},
  {en: "to go out", pr: "ausgehen", pe: "ist ausgegangen"},
  {en: "to come back", pr: "zurückkommen", pe: "ist zurückgekommen"},
  {en: "to fall", pr: "fallen", pe: "ist gefallen"},
  {en: "to happen", pr: "passieren", pe: "ist passiert"}
];