// Word list for Word Practice Tool
// Structure: { [level]: { [kapitel]: [ {question, answer}, ... ] } }
export const wordList = {
  A1: {
    1: [
      { question: "Haus", answer: "house" },
      { question: "Baum", answer: "tree" },
      { question: "Tisch", answer: "table" }
    ],
    2: [
      { question: "Stuhl", answer: "chair" },
      { question: "Buch", answer: "book" },
      { question: "Fenster", answer: "window" }
    ],
    3: [
      { question: "Tür", answer: "door" },
      { question: "Auto", answer: "car" },
      { question: "Straße", answer: "street" }
    ]
    // ...add more Kapitel as needed
  },
  A2: {
    1: [
      { question: "Familie", answer: "The family" },
      { question: "geboren sein", answer: "to be born" },
      { question: "geschieden", answer: "divorced" },
      { question: "heiraten", answer: "to marry" },
      { question: "die Hochzeit", answer: "The wedding" },
      { question: "romantisch", answer: "romantic" },
      { question: "der Rentner", answer: "The male pensioner" },
      { question: "die Rentnerin", answer: "The female pensioner" },
      { question: "Beruf und Uni", answer: "Profession and university" },
      { question: "die Ausbildung", answer: "the training, education" },
      { question: "ab schließen, er schließt ab, hat abgeschlossen", answer: "to complete/to finish (She has completed her training.)" },
      { question: "beenden", answer: "to end, to finish" },
      { question: "die Arbeit (Das war viel Arbeit.)", answer: "The work (That was a lot of work.)" },
      { question: "die Überstunde", answer: "The overtime hour" },
      { question: "der Augenoptiker", answer: "The optician (male)" },
      { question: "die Augenoptikerin", answer: "The optician (female)" },
      { question: "der Bankkaufmann, er", answer: "The banker (male)" },
      { question: "die Bankkauffrau", answer: "The banker (female)" },
      { question: "Biologie (Sg. ohne Artikel) (Ich studiere Biologie.)", answer: "Biology (singular without article) (I study biology.)" },
      { question: "Mathematik (Sg. ohne Artikel)", answer: "Mathematics (singular without article)" },
      { question: "die Note", answer: "The grade, the mark" },
      { question: "wohnen", answer: "to live/to reside" },
      { question: "mieten", answer: "to rent" },
      { question: "renovieren", answer: "to renovate" },
      { question: "das Stadtzentrum, Stadtzentren", answer: "The city center" },
      { question: "auf dem Land leben", answer: "to live in the countryside" },
      { question: "weiter suchen", answer: "to continue searching" },
      { question: "zusammen leben", answer: "to live together" },
      { question: "Freizeit", answer: "The free time/the leisure time" },
      { question: "vorschlagen, er schlägt vor, hat vorgeschlagen", answer: "to suggest/to propose (he suggests, has suggested)" },
      { question: "absagen", answer: "to cancel" },
      { question: "zusagen", answer: "to promise, accept, confirm" },
      { question: "einverstanden sein (Kommst du? - Einverstanden.)", answer: "to agree (Are you coming? - Agreed.)" },
      { question: "einen Plan ändern", answer: "to change a plan" },
      { question: "der Verein", answer: "The club, the association" },
      { question: "(sich) anmelden", answer: "to signin, Enroll, register" },
      { question: "teilnehmen, er nimmt teil, hat teilgenommen", answer: "to take part, to participate, he participates, has participated" },
      { question: "gemeinsam", answer: "together, common" },
      { question: "organisieren", answer: "to organize" },
      { question: "der Flohmarkt", answer: "The flea market, farmer's market" },
      { question: "liegen, er liegt, hat gelegen (Er liegt am Wochenende gern auf dem Sofa.)", answer: "to lie/to be located (He likes to lie on the sofa on the weekend.)" },
      { question: "das Pferd", answer: "The horse" },
      { question: "reiten, er reitet, ist geritten", answer: "to ride (a horse)" },
      { question: "spannend", answer: "exciting" },
      { question: "im Restaurant", answer: "in the restaurant" },
      { question: "der Aufenthalt", answer: "stay" },
      { question: "der Eingang", answer: "The entrance" },
      { question: "empfangen, er empfängt, hat empfangen", answer: "to receive, to welcome, he receives, has received" },
      { question: "der Platz (Ein Kellner führt Sie zum Platz.)", answer: "place, seat (A waiter leads you to your seat.)" },
      { question: "(sich) informieren (über + A.)", answer: "to inform (oneself) (about)" },
      { question: "auswählen", answer: "to choose/to select" },
      { question: "die Reservierung", answer: "The reservation" },
      { question: "spätestens (Ich komme spätenstens um drei Uhr.)", answer: "at the latest (I'll come at three o'clock at the latest.)" },
      { question: "bitter", answer: "bitter" },
      { question: "salzig", answer: "salty" },
      { question: "sauer", answer: "sour" },
      { question: "scharf", answer: "spicy, hot" },
      { question: "das WC", answer: "The toilet, the restroom" },
      { question: "weiterhelfen, er hilft weiter, hat weitergeholfen", answer: "to help further, he helps, has helped" },
      { question: "aus sein", answer: "to be off (Phones must be off.)" },
      { question: "die Zigarette", answer: "The cigarette" },
      { question: "mit allen Sinnen lernen", answer: "to learn with all the senses" },
      { question: "fühlen", answer: "to feel" },
      { question: "der Gegenstand", answer: "The object, the item" },
      { question: "der Sinn", answer: "The sense" },
      { question: "zuhören", answer: "to listen" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "die Angst (Ich habe Angst.)", answer: "The fear (I'm afraid/I have fear.)" },
      { question: "die Grippe", answer: "The flu (He has the flu.)" },
      { question: "das Handy", answer: "The cell phone" },
      { question: "fast", answer: "almost" },
      { question: "also (Meine Mutter ist Italienerin, mein Vater ist Österreicher. Ich habe also zwei Muttersprachen.)", answer: "so, therefore (My mother is Italian, my father is Austrian. So, I have two mother tongues.)" },
      { question: "fließend", answer: "fluent" },
      { question: "eine Sprache fließend sprechen", answer: "to speak a language fluently" },
      { question: "begründen", answer: "to justify, to give reasons for" },
      { question: "rufen, er ruft, hat gerufen", answer: "to call" },
      { question: "ganz (ganz am Ende)", answer: "whole, completely (right at the end)" },
      { question: "Mal sehen.", answer: "Let's see." },
      { question: "weil (Marvin kommt später, weil er arbeiten muss.)", answer: "because (Marvin comes later because he has to work.)" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Ergänzen Sie die Sätze.", answer: "Complete the sentences." },
      { question: "Früher habe ich im Stadtzentrum gewohnt.", answer: "I used to live in the city center." },
      { question: "Jetzt lebe ich mit meinem Freund zusammen.", answer: "Now I live together with my boyfriend." },
      { question: "Wir haben ein Haus auf dem Land gemietet.", answer: "We rented a house in the countryside." },
      { question: "Es ist sehr alt und wir haben es lange renoviert.", answer: "It is very old and we renovated it for a long time." },
      { question: "Ergänzen Sie je drei passende Wörter.", answer: "Add three suitable words each." },
      { question: "Familie", answer: "family" },
      { question: "der Bruder", answer: "The brother" },
      { question: "der Vater", answer: "the father" },
      { question: "die Schwester", answer: "the sister" },
      { question: "die Mutter", answer: "the mother" },
      { question: "Beruf", answer: "The profession/The job" },
      { question: "der Arzt", answer: "the doctor" },
      { question: "der Ingenieur", answer: "the engineer" },
      { question: "die Krankenschwester", answer: "the nurse" },
      { question: "die Kollegen", answer: "the colleagues" },
      { question: "wohnen", answer: "to live, to reside" },
      { question: "das Zimmer", answer: "the room" },
      { question: "der Balkon", answer: "the balcony" },
      { question: "das Apartment", answer: "the apartment" },
      { question: "das Fenster", answer: "the window" },
      { question: "Freizeit", answer: "Leisure time" },
      { question: "Freunde treffen", answer: "meet friends" },
      { question: "der Film", answer: "the film" },
      { question: "joggen", answer: "to jog" },
      { question: "das Spiel", answer: "the game" },
      { question: "Restaurant", answer: "restaurant" },
      { question: "die Rechnung", answer: "the bill" },
      { question: "der Kellner", answer: "the waiter" },
      { question: "die Bestellung", answer: "the order" },
      { question: "die Speisekarte", answer: "the menu" }
    ],
    2: [
      { question: "Erde", answer: "earth" },
      { question: "Luft", answer: "air" },
      { question: "Himmel", answer: "sky" }
    ]
    // ...add more Kapitel as needed
  },
  B1: {
    1: [
      { question: "Sonne", answer: "sun" },
      { question: "Mond", answer: "moon" },
      { question: "Stern", answer: "star" }
    ],
    2: [
      { question: "Blume", answer: "flower" },
      { question: "Gras", answer: "grass" },
      { question: "Wald", answer: "forest" }
    ]
    // ...add more Kapitel as needed
  }
};
