// Word list for Word Practice Tool
// Structure: { [level]: { [kapitel]: [ {question, answer}, ... ] } }
export const wordList = {
  A1: {
    1: [
      { question: "Haus", answer: "house" },
      { question: "Baum", answer: "tree" },
      { question: "Tisch", answer: "table" }
    ],
    2: [
      { question: "Stuhl", answer: "chair" },
      { question: "Buch", answer: "book" },
      { question: "Fenster", answer: "window" }
    ],
    3: [
      { question: "Tür", answer: "door" },
      { question: "Auto", answer: "car" },
      { question: "Straße", answer: "street" }
    ]
    // ...add more Kapitel as needed
  },
  A2: {
    1: [
      { question: "Familie", answer: "The family" },
      { question: "geboren sein", answer: "to be born" },
      { question: "geschieden", answer: "divorced" },
      { question: "heiraten", answer: "to marry" },
      { question: "die Hochzeit", answer: "The wedding" },
      { question: "romantisch", answer: "romantic" },
      { question: "der Rentner", answer: "The male pensioner" },
      { question: "die Rentnerin", answer: "The female pensioner" },
      { question: "Beruf und Uni", answer: "Profession and university" },
      { question: "die Ausbildung", answer: "the training, education" },
      { question: "ab schließen", answer: "to complete/to finish" },
      { question: "beenden", answer: "to end, to finish" },
      { question: "die Arbeit", answer: "The work" },
      { question: "die Überstunde", answer: "The overtime hour" },
      { question: "der Augenoptiker", answer: "The optician (male)" },
      { question: "die Augenoptikerin", answer: "The optician (female)" },
      { question: "der Bankkaufmann, er", answer: "The banker (male)" },
      { question: "die Bankkauffrau", answer: "The banker (female)" },
      { question: "Biologie", answer: "Biology" },
      { question: "Mathematik", answer: "Mathematics" },
      { question: "die Note", answer: "The grade, the mark" },
      { question: "wohnen", answer: "to live/to reside" },
      { question: "mieten", answer: "to rent" },
      { question: "renovieren", answer: "to renovate" },
      { question: "das Stadtzentrum, Stadtzentren", answer: "The city center" },
      { question: "auf dem Land leben", answer: "to live in the countryside" },
      { question: "weiter suchen", answer: "to continue searching" },
      { question: "zusammen leben", answer: "to live together" },
      { question: "Freizeit", answer: "The free time/the leisure time" },
      { question: "vorschlagen", answer: "to suggest/to propose" },
      { question: "absagen", answer: "to cancel" },
      { question: "zusagen", answer: "to promise, accept, confirm" },
      { question: "einverstanden sein", answer: "to agree" },
      { question: "einen Plan ändern", answer: "to change a plan" },
      { question: "der Verein", answer: "The club, the association" },
      { question: "(sich) anmelden", answer: "to signin, Enroll, register" },
      { question: "teilnehmen", answer: "to take part, to participate" },
      { question: "gemeinsam", answer: "together, common" },
      { question: "organisieren", answer: "to organize" },
      { question: "der Flohmarkt", answer: "The flea market, farmer's market" },
      { question: "liegen", answer: "to lie/to be located" },
      { question: "das Pferd", answer: "The horse" },
      { question: "reiten", answer: "to ride" },
      { question: "spannend", answer: "exciting" },
      { question: "im Restaurant", answer: "in the restaurant" },
      { question: "der Aufenthalt", answer: "stay" },
      { question: "der Eingang", answer: "The entrance" },
      { question: "empfangen", answer: "to receive, to welcome" },
      { question: "der Platz", answer: "place, seat" },
      { question: "(sich) informieren (über + A.)", answer: "to inform (oneself) about" },
      { question: "auswählen", answer: "to choose/to select" },
      { question: "die Reservierung", answer: "The reservation" },
      { question: "spätestens", answer: "at the latest" },
      { question: "bitter", answer: "bitter" },
      { question: "salzig", answer: "salty" },
      { question: "sauer", answer: "sour" },
      { question: "scharf", answer: "spicy, hot" },
      { question: "das WC", answer: "The toilet, the restroom" },
      { question: "weiterhelfen", answer: "to help further" },
      { question: "aus sein", answer: "to be off" },
      { question: "die Zigarette", answer: "The cigarette" },
      { question: "mit allen Sinnen lernen", answer: "to learn with all the senses" },
      { question: "fühlen", answer: "to feel" },
      { question: "der Gegenstand", answer: "The object, the item" },
      { question: "der Sinn", answer: "The sense" },
      { question: "zuhören", answer: "to listen" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "die Angst", answer: "The fear" },
      { question: "die Grippe", answer: "The flu" },
      { question: "das Handy", answer: "The cell phone" },
      { question: "fast", answer: "almost" },
      { question: "also", answer: "so, therefore" },
      { question: "fließend", answer: "fluent" },
      { question: "eine Sprache fließend sprechen", answer: "to speak a language fluently" },
      { question: "begründen", answer: "to justify, to give reasons for" },
      { question: "rufen, er ruft, hat gerufen", answer: "to call" },
      { question: "ganz", answer: "whole, completely" },
      { question: "Mal sehen.", answer: "Let's see." },
      { question: "weil", answer: "because" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Ergänzen", answer: "to complete" },
      { question: "Früher habe ich im Stadtzentrum gewohnt.", answer: "I used to live in the city center." },
      { question: "Jetzt lebe ich mit meinem Freund zusammen.", answer: "Now I live together with my boyfriend." },
      { question: "Wir haben ein Haus auf dem Land gemietet.", answer: "We rented a house in the countryside." },
      { question: "Es ist sehr alt und wir haben es lange renoviert.", answer: "It is very old and we renovated it for a long time." },
      { question: "Ergänzen Sie je drei passende Wörter.", answer: "Add three suitable words each." },
      { question: "Familie", answer: "family" },
      { question: "der Bruder", answer: "The brother" },
      { question: "der Vater", answer: "the father" },
      { question: "die Schwester", answer: "the sister" },
      { question: "die Mutter", answer: "the mother" },
      { question: "Beruf", answer: "The profession/The job" },
      { question: "der Arzt", answer: "the doctor" },
      { question: "der Ingenieur", answer: "the engineer" },
      { question: "die Krankenschwester", answer: "the nurse" },
      { question: "die Kollegen", answer: "the colleagues" },
      { question: "wohnen", answer: "to live, to reside" },
      { question: "das Zimmer", answer: "the room" },
      { question: "der Balkon", answer: "the balcony" },
      { question: "das Apartment", answer: "the apartment" },
      { question: "das Fenster", answer: "the window" },
      { question: "Freizeit", answer: "Leisure time" },
      { question: "Freunde treffen", answer: "meet friends" },
      { question: "der Film", answer: "the film" },
      { question: "joggen", answer: "to jog" },
      { question: "das Spiel", answer: "the game" },
      { question: "Restaurant", answer: "restaurant" },
      { question: "die Rechnung", answer: "the bill" },
      { question: "der Kellner", answer: "the waiter" },
      { question: "die Bestellung", answer: "the order" },
      { question: "die Speisekarte", answer: "the menu" }
    ],
    2: [
      { question: "der Abschluss", answer: "the graduation/the degree/the qualification" },
      { question: "der Schulabschluss", answer: "the school leaving qualification, high school diploma" },
      { question: "das Abitur", answer: "German higher education  entrance qualification" },
      { question: "das Zeugnis", answer: "the report card/the certificate" },
      { question: "der Direktor", answer: "director (male)" },
      { question: "die Direktorin", answer: "director (female)" },
      { question: "der Schüler", answer: "student (male)" },
      { question: "die Schülerin", answer: "student (female)" },
      { question: "die Klasse", answer: "the class" },
      { question: "das Klassenzimmer", answer: "the classroom" },
      { question: "die Dauer", answer: "the duration" },
      { question: "die Unterrichtszeit", answer: "the class time/the teaching time" },
      { question: "der Stundenplan", answer: "the timetable/the schedule" },
      { question: "die Fremdsprache", answer: "the foreign language" },
      { question: "die Cafeteria, Cafeterien", answer: "the cafeteria, caferterias" },
      { question: "der Schulweg", answer: "the way to school/the school commute" },
      { question: "die Klassenfahrt", answer: "the class trip" },
      { question: "die Ferien", answer: "the holidays/the vacation" },
      { question: "die Schuluniform", answer: "the school uniform" },
      { question: "streng", answer: "strict" },
      { question: "die Vorbereitung", answer: "the preparation" },
      { question: "üben", answer: "to practice" },
      { question: "der Vokabeltest", answer: "the vocabulary test" },
      { question: "Schulfächer", answer: "School subjects" },
      { question: "das Fach", answer: "the school subject" },
      { question: "Lieblings", answer: "favorite" },
      { question: "Chemie", answer: "the chemistry" },
      { question: "Geografie", answer: "the geography" },
      { question: "Geschichte", answer: "the history" },
      { question: "Informatik", answer: "the computer science" },
      { question: "Latein", answer: "the Latin" },
      { question: "Kunsterziehung/Kunst", answer: "the art education/the art" },
      { question: "Mathematik/Mathe", answer: "the mathematics/the math" },
      { question: "Physik", answer: "the physics" },
      { question: "Sozialkunde", answer: "the social studies/the civics" },
      { question: "Wirschaft", answer: "Business" },
      { question: "die AG", answer: "type of company (stock corporation) or a school club (Arbeitsgemeinschaft)" },
      { question: "Schultypen", answer: "School types" },
      { question: "die Grundschule", answer: "the primary school" },
      { question: "die Hauptschule", answer: "type of secondary school" },
      { question: "die Realschule", answer: "type of secondary school" },
      { question: "das Gymnasium, Gymnasien", answer: "a type of secondary school leading to the Abitur" },
      { question: "die Gesamtschule", answer: "the comprehensive school" },
      { question: "die Berufsschule", answer: "the vocational school" },
      { question: "das Schulsystem", answer: "the school system" },
      { question: "das Bundesland", answer: "the federal state" },
      { question: "Berufe", answer: "Professions" },
      { question: "der Altenpfleger", answer: "geriatric nurse (male)" },
      { question: "die Arzthelferin", answer: "medical assistant (female)" },
      { question: "das Au-pair", answer: "the au pair" },
      { question: "der Englischlehrer", answer: "the English teacher (male)" },
      { question: "die Gärtnerin", answer: "the gardener (female)" },
      { question: "der Grafiker", answer: "the graphic designer (male)" },
      { question: "der Hotelkaufmann", answer: "the hotel manager (male)" },
      { question: "die Hotelkauffrau", answer: "the hotel manager (female)" },
      { question: "die Krankenschwester", answer: "the nurse (female)" },
      { question: "der Krankenpfleger", answer: "the nurse (male)" },
      { question: "Arbeit und Beruf", answer: "Work and Career" },
      { question: "die Arbeitswelt", answer: "the world of work" },
      { question: "der/die Auszubildende", answer: "the apprentice/the trainee" },
      { question: "der Azubi", answer: "the trainee/the apprentice (Informal)" },
      { question: "die Lehre", answer: "the apprenticeship" },
      { question: "die Berufserfahrung", answer: "the professional experience/the work experience" },
      { question: "die Erfahrung", answer: "the experience" },
      { question: "das Berufsleben", answer: "the working life/the professional life" },
      { question: "das Handwerk", answer: "to skilled trade/the craft" },
      { question: "jobben", answer: "to work (casual/side job/to temp)" },
      { question: "die Messe", answer: "the trade fair/the exhibition" },
      { question: "die Arztpraxis, Arztpraxen", answer: "the doctor's office/the doctor's offices" },
      { question: "das Reisebüro", answer: "the travel agency" },
      { question: "die Werbeagentur", answer: "the advertising agency" },
      { question: "Universität", answer: "University" },
      { question: "Jura (Sie hat Jura studiert.)", answer: "the law (She studied law.)" },
      { question: "Medizin", answer: "the medicine" },
      { question: "die Vorlesung", answer: "the lecture" },
      { question: "eine Vorlesung besuchen", answer: "to attend a lecture" },
      { question: "die Meinung sagen", answer: "express your opinion" },
      { question: "die Meinung", answer: "the opinion" },
      { question: "ablehnen", answer: "to reject/to decline" },
      { question: "zustimmen", answer: "to agree, to consent" },
      { question: "nützlich", answer: "useful" },
      { question: "witzig", answer: "funny/witty" },
      { question: "furchtbar", answer: "terrible/awful" },
      { question: "schlecht", answer: "bad" },
      { question: "wütend", answer: "furious/angry" },
      { question: "Das sehe ich anders.", answer: "I see that differently." },
      { question: "Das war bei mir auch so.", answer: "That was the same for me too." },
      { question: "die Hauptsache", answer: "the main thing " },
      { question: "überraschen", answer: "to surprise" },
      { question: "überrascht sein", answer: "to be surprised" },
      { question: "die Gemeinsamkeit", answer: "the commonality/the similarity" },
      { question: "der Unterschied", answer: "the difference" },
      { question: "wahrscheinlich", answer: "probably" },
      { question: "wenigstens", answer: "at least" },
      { question: "ziemlich", answer: "quite/pretty" },
      { question: "zum Beispiel", answer: "for example" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "aus|schlafen, er schläft aus, hat ausgeschlafen", answer: "to sleep in, he sleeps in, has slept in" },
      { question: "die Behinderung", answer: "the disability" },
      { question: "der Rollstuhl", answer: "the wheelchair" },
      { question: "ehrlich", answer: "honest/honestly" },
      { question: "die Erholung", answer: "the recovery/the relaxation" },
      { question: "die Erinnerung", answer: "the memory" },
      { question: "die Weltreise", answer: "the world trip/the world tour" },
      { question: "erwachsen", answer: "adult/grown-up" },
      { question: "unabhängig", answer: "independent" },
      { question: "freiwillig", answer: "voluntary" },
      { question: "sozial", answer: "social" },
      { question: "die Grafik", answer: "the graphic/the chart (see the graphic." },
      { question: "heute", answer: "today" },
      { question: "erst mal", answer: "first/for now" },
      { question: "paar", answer: "a few/couple" },
      { question: "der Kontakt", answer: "the contact" },
      { question: "verlieren", answer: "to lose" },
      { question: "je", answer: "each, respectively" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Ergänzen Sie Wörter.", answer: "Complete word },
      { question: "Sozialkunde", answer: "Social Studies" },
      { question: "Chemie", answer: "Chemistry" },
      { question: "Hauptschule", answer: "Secondary School" },
      { question: "Universität", answer: "University" },
      { question: "Latin", answer: "Latin" },
      { question: "Erwachsen", answer: "Adult" },
      { question: "Bundesland", answer: "Federal State" },
      { question: "Erfahrung", answer: "Experience" },
      { question: "Reisebüro", answer: "Travel Agency" },
      { question: "Hotelkaufmann", answer: "Hotel Manager (male)" },
      { question: "Fremdsprache", answer: "Foreign Language" },
      { question: "Ehrlich", answer: "Honest" },
      { question: "Arztpraxis", answer: "Doctor's Office" },
      { question: "Realschule", answer: "Secondary School" },
      { question: "Berufsschule", answer: "Vocational School" },
      { question: "Erst mal", answer: "First of all" },
      { question: "Informatik", answer: "Computer Science" },
      { question: "Typ", answer: "Type" }
    ],
    3: [
      { question: "Medien und Geräte", answer: "The media and devices" },
      { question: "das E-Book", answer: "The e-book" },
      { question: "der E-Book-Reader", answer: "The e-book reader" },
      { question: "der Laptop", answer: "The laptop" },
      { question: "das Radio", answer: "The radio" },
      { question: "das Smartphone", answer: "The smartphone" },
      { question: "die Spielekonsole", answer: "The games console" },
      { question: "das Tablet", answer: "The tablet" },
      { question: "der Bildschirm", answer: "The screen/monitor" },
      { question: "die Tastatur", answer: "The keyboard" },
      { question: "die Maus", answer: "The mouse" },
      { question: "das Kabel", answer: "The cable" },
      { question: "der Lautsprecher", answer: "The loudspeaker/speaker" },
      { question: "die Webseite", answer: "The website" },
      { question: "der Link", answer: "The link" },
      { question: "der Kontakt", answer: "The contact" },
      { question: "in Kontakt bleiben", answer: "To stay in contact" },
      { question: "Aktivitäten mit Medien", answer: "Activities with media" },
      { question: "an sein", answer: "To be on" },
      { question: "an klicken", answer: "To click (on)" },
      { question: "tippen", answer: "To type" },
      { question: "checken", answer: "To check" },
      { question: "downloaden", answer: "To download" },
      { question: "herunterladen", answer: "To download" },
      { question: "hoch laden", answer: "To upload" },
      { question: "kopieren", answer: "To copy" },
      { question: "löschen", answer: "To delete" },
      { question: "mailen", answer: "To email" },
      { question: "senden", answer: "To send" },
      { question: "weiter leiten", answer: "To forward" },
      { question: "bloggen", answer: "To blog" },
      { question: "der Blogbeitrag", answer: "The blog post" },
      { question: "chatten", answer: "To chat" },
      { question: "posten", answer: "To post" },
      { question: "teilen", answer: "To share" },
      { question: "Fotos teilen", answer: "To share photos" },
      { question: "Dinge vergleichen", answer: "To compare things" },
      { question: "der Vergleich", answer: "The comparison" },
      { question: "leicht", answer: "light, easy" },
      { question: "als", answer: "than" },
      { question: "wie", answer: "as" },
      { question: "genauso", answer: "just as/equally" },
      { question: "über Arbeit sprechen", answer: "To talk about work" },
      { question: "das Start-Up", answer: "The start-up" },
      { question: "gründen", answer: "To found/to start" },
      { question: "ein Start-Up gründen", answer: "To found a start-up" },
      { question: "der/die Studierende", answer: "The student (male/female)" },
      { question: "entwickeln (eine App entwickeln)", answer: "To develop (To develop an app)" },
      { question: "programmieren", answer: "To program" },
      { question: "Meinung äußern", answer: "To express an opinion" },
      { question: "die Umfrage", answer: "The survey" },
      { question: "kommentieren", answer: "To comment" },
      { question: "meinen", answer: "To mean/think" },
      { question: "mit teilen", answer: "To inform/communicate/to share" },
      { question: "kritisch", answer: "critical" },
      { question: "blöd", answer: "stupid/silly" },
      { question: "peinlich", answer: "embarrassing" },
      { question: "privat", answer: "private" },
      { question: "dass", answer: "that" },
      { question: "Kino und Filme", answer: "Cinema and films/movies" },
      { question: "der Actionfilm", answer: "The action film/movie" },
      { question: "der Fantasy-Film", answer: "The fantasy film/movie" },
      { question: "die Komödie", answer: "The comedy" },
      { question: "der Krimi", answer: "The crime film/mystery" },
      { question: "der Liebesfilm", answer: "The romance film/love story" },
      { question: "der Thriller", answer: "The thriller" },
      { question: "die Filmmusik", answer: "The film music/soundtrack" },
      { question: "die Handlung", answer: "The plot/action/story" },
      { question: "Worum geht es im Film?", answer: "What is the film about?" },
      { question: "der Trailer", answer: "The trailer" },
      { question: "die Hauptperson", answer: "The main character" },
      { question: "das Talent", answer: "The talent" },
      { question: "der Humor", answer: "The humor" },
      { question: "der Witz", answer: "The joke" },
      { question: "spielen", answer: "To play/to be set" },
      { question: "einfach", answer: "just/simply" },
      { question: "logisch", answer: "logical" },
      { question: "real", answer: "real" },
      { question: "andere wichtige Wörter und Wendungen", answer: "Other important words and phrases" },
      { question: "aus probieren", answer: "To try out/test out" },
      { question: "gewinnen", answer: "To win" },
      { question: "lachen", answer: "To laugh" },
      { question: "weinen", answer: "To cry" },
      { question: "flüstern", answer: "To whisper" },
      { question: "dumm, dümmer, am dümmsten", answer: "stupid, more stupid, most stupid" },
      { question: "fröhlich", answer: "cheerful/happy" },
      { question: "nah, näher, am nächsten", answer: "near, nearer, nearest" },
      { question: "schwierig", answer: "difficult/hard" },
      { question: "still", answer: "quiet/still" },
      { question: "vorsichtig", answer: "careful" },
      { question: "der Enkel", answer: "The grandson" },
      { question: "die Enkelin", answer: "The granddaughter" },
      { question: "die Freundschaft", answer: "The friendship" },
      { question: "die Kindheit", answer: "The childhood" },
      { question: "das Schicksal", answer: "The fate/destiny" },
      { question: "die Sorge", answer: "The worry" },
      { question: "sterben", answer: "To die" },
      { question: "tot", answer: "dead" },
      { question: "das Tier", answer: "The animal" },
      { question: "manche, mancher", answer: "some/some people" },
      { question: "mehrmals", answer: "several times" },
      { question: "plötzlich", answer: "suddenly" },
      { question: "überhaupt", answer: "at all" },
      { question: "unbedingt", answer: "absolutely/definitely" },
      { question: "zuletzt", answer: "lastly/finally/most recently" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Welche Filme gibt es? Ergänzen Sie die Buchstaben.", answer: "Which films are there? Fill in the letters." },
      { question: "die Komödie", answer: "The comedy" },
      { question: "der Thriller", answer: "The thriller" },
      { question: "der Actionfilm", answer: "The action film/movie" },
      { question: "der Krimi", answer: "The crime film/mystery" },
      { question: "der Fantasy-Film", answer: "The fantasy film/movie" },
      { question: "der Liebesfilm", answer: "The romance film/love story" },
      { question: "Was kann man damit machen? Notieren Sie möglichst viele Verben.", answer: "What can you do with that? Note as many verbs as possible." },
      { question: "die Mail", answer: "The email" },
      { question: "checken", answer: "to check" },
      { question: "senden", answer: "to send" },
      { question: "mailen", answer: "to email" },
      { question: "weiterleiten", answer: "to forward" },
      { question: "löschen", answer: "to delete" },
      { question: "kopieren", answer: "to copy" },
      { question: "die App", answer: "The app" },
      { question: "entwickeln", answer: "to develop" },
      { question: "downloaden", answer: "to download" },
      { question: "herunterladen", answer: "to download" },
      { question: "hochladen", answer: "to upload" },
      { question: "das Foto", answer: "The photo" },
      { question: "teilen", answer: "to share" },
      { question: "löschen", answer: "to delete" },
      { question: "kopieren", answer: "to copy" },
      { question: "hochladen", answer: "to upload" },
      { question: "das Smartphone", answer: "The smartphone" },
      { question: "tippen", answer: "to type" },
      { question: "chatten", answer: "to chat" },
      { question: "an sein", answer: "to be on" },
      { question: "downloaden", answer: "to download" },
      { question: "herunterladen", answer: "to download" },
      { question: "telefonieren", answer: "to make a phone call - implied" },
      { question: "surfen", answer: "to surf the web - implied" }
      ]
  },
  B1: {
    1: [
      { question: "Sonne", answer: "sun" },
      { question: "Mond", answer: "moon" },
      { question: "Stern", answer: "star" }
    ],
    2: [
      { question: "Blume", answer: "flower" },
      { question: "Gras", answer: "grass" },
      { question: "Wald", answer: "forest" }
    ]
    // ...add more Kapitel as needed
  }
};
