// Word list for Word Practice Tool
// Structure: { [level]: { [kapitel]: [ {question, answer}, ... ] } }
export const wordList = {
  A1: {
    1: [
      { question: "sich vorstellen", answer: "Introduce yourself" },
      { question: "der Name", answer: "the name" },
      { question: "mein (Mein Name ist...)", answer: "my  (My name is...)" },
      { question: "dein (Wie ist dein Name?)", answer: "your (informal) (What is your name?)" },
      { question: "Ihr (Wie ist Ihr Name?)", answer: "your (formal) (What is your name?)" },
      { question: "der Vorname", answer: "the first name" },
      { question: "der Nachname", answer: "the last name" },
      { question: "buchstabieren", answer: "to spell" },
      { question: "heißen", answer: "to be called" },
      { question: "sein, er ist", answer: "to be, he is" },
      { question: "wohnen", answer: "to live" },
      { question: "in (Ich wohne in...)", answer: "in (I live in...)" },
      { question: "die Stadt, e", answer: "the city" },
      { question: "wie (Wie heißt du?)", answer: "how (What are you called?)" },
      { question: "wer (Wer bist du?) ", answer: "who (Who are you?)" },
      { question: "wo (Wo wohnst du?) ", answer: "where (Where do you live?)" },
      { question: "woher (Woher kommst du?) ", answer: "where from (Where are you from?)" },
      { question: "Das ist Herr/Frau...", answer: "This is Mr./Mrs...." },
      { question: "die E-Mail-Adresse", answer: "the email address" },
      { question: "die Handynummer", answer: "the mobile number" },
      { question: "die Telefonnummer", answer: "the phone numbe" },
      { question: "Länder und Sprachen", answer: "Countries and Languages" },
      { question: "Deutschland", answer: "Germany" },
      { question: "Österreich", answer: "Austria" },
      { question: "die Schweiz", answer: "Switzerland" },
      { question: "das Land, er", answer: "the country" },
      { question: "kommen", answer: "to come" },
      { question: "aus (Er kommt aus Spanien.)", answer: "from (He comes from Spain.)" },
      { question: "die Sprache", answer: "the language" },
      { question: "lernen", answer: "to learn" },
      { question: "sprechen, er spricht", answer: "to speak, he speaks" },
      { question: "Welche Sprachen sprechen Sie?", answer: "What languages do you speak?" },
      { question: "Deutsch", answer: "German" },
      { question: "grüßen und verabschieden", answer: "to greet and say goodbye" },
      { question: "Hallo!", answer: "Hello!" },
      { question: "Guten Morgen", answer: "Good morning" },
      { question: "Guten Tag", answer: "Good day" },
      { question: "Guten Abend", answer: "Good evening" },
      { question: "Gute Nacht", answer: "Good night" },
      { question: "Tschüs", answer: "Bye (informal)" },
      { question: "Ciao", answer: "Bye (informal)" },
      { question: "Bis bald!", answer: "See you soon!" },
      { question: "Auf Wiedersehen", answer: "Goodbye (formal)" },
      { question: "nach dem Befinden fragen", answer: "to ask about one's well-being" },
      { question: "Wie geht's?", answer: "How are you?" },
      { question: "Sehr gut", answer: "Very good" },
      { question: "Danke, gut", answer: "Thanks, good" },
      { question: "Ganz gut", answer: "Pretty good" },
      { question: "Zahlen", answer: "Numbers" },
      { question: "die Zahl", answer: "the number" },
      { question: "null", answer: "zero" },
      { question: "eins", answer: "one" },
      { question: "zwei", answer: "two" },
      { question: "drei", answer: "three" },
      { question: "vier", answer: "four" },
      { question: "fünf", answer: "five" },
      { question: "sechs", answer: "six" },
      { question: "sieben", answer: "seven" },
      { question: "acht", answer: "eight" },
      { question: "neun", answer: "nine" },
      { question: "zehn", answer: "ten" },
      { question: "elf", answer: "eleven" },
      { question: "zwölf", answer: "twelve" },
      { question: "dreizehn", answer: "thirteen" },
      { question: "vierzehn", answer: "fourteen" },
      { question: "fünfzehn", answer: "fifteen" },
      { question: "sechzehn", answer: "sixteen" },
      { question: "siebzehn", answer: "seventeen" },
      { question: "achtzehn", answer: "eighteen" },
      { question: "neunzehn", answer: "nineteen" },
      { question: "zwanzig", answer: "twenty" },
      { question: "im Kurs", answer: "in the class" },
      { question: "fragen", answer: "to ask" },
      { question: "die Antwort", answer: "the answer" },
      { question: "hören", answer: "to hear/listen" },
      { question: "lesen, er liest", answer: "to read, he reads" },
      { question: "machen", answer: "to do/make" },
      { question: "notieren", answer: "to note" },
      { question: "raten, er rät", answer: "to guess, he guesses" },
      { question: "sagen", answer: "to say" },
      { question: "sammeln", answer: "to collect" },
      { question: "schreiben", answer: "to write" },
      { question: "spielen", answer: "to play" },
      { question: "zulordnen", answer: "to assign/match" },
      { question: "der Partner", answer: "the partner (male)" },
      { question: "die Partnerinen", answer: "the partner (female)" },
      { question: "die Person", answer: "the person" },
      { question: "der Text", answer: "the text" },
      { question: "das Wort", answer: "the word" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "die Autobahn", answer: "the highway" },
      { question: "die Flasche", answer: "the bottle" },
      { question: "der Kindergarten", answer: "the kindergarten" },
      { question: "der Koffer", answer: "the suitcase" },
      { question: "Entschuldigung, noch einmal, bitte", answer: "Excuse me, once more, please" },
      { question: "Wie bitte?", answer: "Pardon? / What did you say?" },
      { question: "Das verstehe ich nicht", answer: "I don't understand that" },
      { question: "Bitte ein bisschen langsamer", answer: "A little slower, please" }
    ],
    2: [
      { question: "In der Freizeit", answer: "In free time" },
      { question: "das Hobby", answer: "hobby, hobbies" },
      { question: "das Buch", answer: "book, books" },
      { question: "das Cafe", answer: "cafe, cafes" },
      { question: "der Computer", answer: "computer, computers" },
      { question: "die Verabredung", answer: "the date, the appointment" },
      { question: "wann (Wann gehen wir ins Café?)", answer: "when (When do we go to the cafe?)" },
      { question: "der Freund", answer: "the friend (male)" },
      { question: "die Freundin", answer: "the girlfriend (female)" },
      { question: "die Leute", answer: "the people" },
      { question: "der Fußball", answer: "the football/soccer" },
      { question: "Tennis spielen", answer: "to play tennis" },
      { question: "joggen", answer: "to jog" },
      { question: "das Kino", answer: "the cinema" },
      { question: "das Theater", answer: "the theater" },
      { question: "das Museum, Museen", answer: "the museum" },
      { question: "die Musik", answer: "the music" },
      { question: "das Schwimmbad", answer: "the swimming pool" },
      { question: "schwimmen", answer: "to swim" },
      { question: "fotografieren", answer: "to photograph" },
      { question: "das Foto", answer: "the photo" },
      { question: "kochen", answer: "to cook" },
      { question: "reisen", answer: "to travel" },
      { question: "singen", answer: "to sing" },
      { question: "tanzen", answer: "to dance" },
      { question: "freihaben, er hat frei", answer: "to have free time, he has free time" },
      { question: "Berufe und Arbeit", answer: "Professions and Work" },
      { question: "arbeiten", answer: "to work" },
      { question: "bei", answer: "at (I work at...)" },
      { question: "der Beruf", answer: "the profession" },
      { question: "von", answer: "from" },
      { question: "Was sind Sie von Beruf?", answer: "What is your profession?" },
      { question: "der Arzt", answer: "the doctor (male)" },
      { question: "die Ärztin", answer: "the doctor (female)" },
      { question: "das Krankenhaus", answer: "the hospital" },
      { question: "der Friseur", answer: "the hairdresser (male)" },
      { question: "die Handwerkerin", answer: "the craftswoman" },
      { question: "der Journalist", answer: "the journalist (male)" },
      { question: "die Kellnerin", answer: "the waitress" },
      { question: "der Koch", answer: "the cook (male)" },
      { question: "die Köchin", answer: "the cook (female)" },
      { question: "der Krankenpfleger", answer: "the nurse (male)" },
      { question: "das Restaurant", answer: "the restaurant" },
      { question: "der Kollege", answer: "the colleague (male)" },
      { question: "die Kollegin", answer: "the colleague (female)" },
      { question: "die Firma, Firmen", answer: "the company" },
      { question: "der Lehrer", answer: "the teacher (male)" },
      { question: "die Schule", answer: "the school" },
      { question: "der Kurs", answer: "the course" },
      { question: "die Mechanikerin", answer: "the mechanic (female)" },
      { question: "der Polizist", answer: "the police officer (male)" },
      { question: "die Studentin", answer: "the student (female)" },
      { question: "studieren", answer: "to study" },
      { question: "die Universität", answer: "the university" },
      { question: "das Seminar", answer: "the seminar" },
      { question: "der Taxifahrer", answer: "the taxi driver (male)" },
      { question: "das Taxi", answer: "the taxi" },
      { question: "das Auto", answer: "the car" },
      { question: "fahren, er fährt", answer: "to drive" },
      { question: "die Verkäuferin", answer: "the saleswoman" },
      { question: "Zeit", answer: "Time" },
      { question: "der Abend", answer: "the evening" },
      { question: "der Nachmittag", answer: "the afternoon" },
      { question: "der Moment", answer: "the moment" },
      { question: "im Moment", answer: "at the moment" },
      { question: "die Stunde", answer: "the hour" },
      { question: "der Tag", answer: "the day" },
      { question: "die Woche", answer: "the week" },
      { question: "pro Woche", answer: "per week" },
      { question: "das Wochenende", answer: "the weekend" },
      { question: "der Wochentag", answer: "the weekday" },
      { question: "das Jahr", answer: "the year, the years" },
      { question: "alt", answer: "old" },
      { question: "Ich bin ... Jahre alt.", answer: "I am ... years old." },
      { question: "der Termin", answer: "the appointment" },
      { question: "morgen", answer: "tomorrow" },
      { question: "nachts", answer: "at night" },
      { question: "meistens", answer: "mostly" },
      { question: "noch", answer: "still, yet" },
      { question: "Wochentage", answer: "Days of the week" },
      { question: "Montag", answer: "Monday" },
      { question: "Dienstag", answer: "Tuesday" },
      { question: "Mittwoch", answer: "Wednesday" },
      { question: "Donnerstag", answer: "Thursday" },
      { question: "Freitag", answer: "Friday" },
      { question: "Samstag", answer: "Saturday" },
      { question: "Sonntag", answer: "Sunday" },
      { question: "Andere wichtige Wörter und Wendungen", answer: "Other important words and phrases" },
      { question: "ja", answer: "yes" },
      { question: "nein", answer: "no" },
      { question: "die Notiz (Machen Sie Notizen.)", answer: "the note (Make notes.)" },
      { question: "das Beispiel", answer: "the example" },
      { question: "der Schlüssel", answer: "the key" },
      { question: "das Wörterbuch, ¨er", answer: "the dictionary" },
      { question: "das Zimmer", answer: "the room" },
      { question: "haben, er hat (Ich habe vier Seminare pro Woche.)", answer: "to have, he has (I have four seminars per week.)" },
      { question: "passen", answer: "to fit" },
      { question: "suchen", answer: "to look for" },
      { question: "warten", answer: "to wait" },
      { question: "alle", answer: "all" },
      { question: "hier", answer: "here" },
      { question: "gern", answer: "gladly, with pleasure" },
      { question: "Ich schwimme gern", answer: "I like to swim." },
      { question: "gehen", answer: "to go" },
      { question: "Es geht so", answer: "It's so-so." },
      { question: "leider", answer: "unfortunately" },
      { question: "Das geht leider nicht", answer: "Unfortunately, that's not possible." },
      { question: "groß", answer: "big, tall" },
      { question: "lustig", answer: "funny" },
      { question: "neu", answer: "new" },
      { question: "super", answer: "great, super" },
      { question: "toll", answer: "great, awesome" },
      { question: "viel", answer: "a lot, much" },
      { question: "wirklich", answer: "really, truly" },
      { question: "Informationen zur Person", answer: "Personal Information" },
      { question: "die Information", answer: "the information" },
      { question: "der Familienname", answer: "the family name" },
      { question: "die Adresse", answer: "the address" },
      { question: "die Straße", answer: "the street" },
      { question: "die Hausnummer", answer: "the house number" },
      { question: "die Postleitzahl", answer: "the postal code" },
      { question: "der Wohnort", answer: "the place of residence" },
      { question: "das Geburtsdatum daten", answer: "the date of birth" },
      { question: "der Geburtsort", answer: "the place of birth" },
      { question: "männlich", answer: "male" },
      { question: "weiblich", answer: "female" },
      { question: "das Formular", answer: "the form" }
    ],
    3: [
      {question: "eine Stadttour", answer: "a city tour" },
      {question: "der Mensch", answer: "the person/human" },
      {question: "das Haus", answer: "the house" },
      {question: "das Rathaus", answer: "the city hall" },
      {question: "das Konzerthaus", answer: "the concert hall" },
      {question: "die Kirche", answer: "the church" },
      {question: "der Turm", answer: "the tower" },
      {question: "das Hotel", answer: "the hotel" },
      {question: "die Brücke", answer: "the bridge" },
      {question: "der Park", answer: "the park" },
      {question: "der Markt", answer: "the market" },
      {question: "der Bahnhof", answer: "the train station" },
      {question: "der Hafen", answer: "the harbor" },
      {question: "der See", answer: "the lake" },
      {question: "der Fluss", answer: "the river" },
      {question: "das Meer", answer: "the sea" },
      {question: "sehen, er sieht (Da sieht man den Hafen.)", answer: "to see, he sees (You can see the harbor there.)" },
      {question: "da (Da ist das Hotel.)", answer: "there (There is the hotel.)" },
      {question: "Das ist", answer: "That is" },
      {question: "interessant", answer: "interesting" },
      {question: "schön", answer: "beautiful" },
      {question: "die Station", answer: "the station" },
      {question: "der Ort", answer: "the place/location" },
      {question: "Maße angeben", answer: "give measurements" },
      {question: "der Meter", answer: "the meter" },
      {question: "der Kilometer", answer: "the kilometer" },
      {question: "lang (Die Brücke ist 12 Kilometer lang.)", answer: "long (The bridge is 12 kilometers long.)" },
      {question: "breit (Das Rathaus ist 111 Meter breit.)", answer: "wide (The town hall is 111 meters wide.)" },
      {question: "hoch (Der Turm ist 132 Meter hoch.)", answer: "high (The tower is 132 meters high.)" },
      {question: "über (Das Haus ist über 100 Jahre alt.)", answer: "over (The house is over 100 years old.)" },
      {question: "die Kosten", answer: "the costs" },
      {question: "der Euro", answer: "the euro" },
      {question: "Verkehrsmittel", answer: "means of transport" },
      {question: "zu Fuß gehen", answer: "to go on foot" },
      {question: "das Fahrrad", answer: "the bicycle" },
      {question: "der Bus", answer: "the bus" },
      {question: "die Straßenbahn", answer: "the streettrain, the tram" },
      {question: "der Zug", answer: "the train" },
      {question: "die U-Bahn", answer: "the U train, the underground train" },
      {question: "die S-Bahn", answer: "the S train, the suburban train" },
      {question: "das Schiff", answer: "the ship" },
      {question: "das Flugzeug", answer: "the airplane" },
      {question: "die Fahrkarte", answer: "the ticket (for transport)" },
      {question: "schnell", answer: "fast" },
      {question: "nach (Der Zug fährt nach Berlin.)", answer: "to (The train goes to Berlin.)" },
      {question: "einen Weg beschreiben", answer: "to describe a way/path" },
      {question: "der Weg", answer: "the way/path" },
      {question: "Wo ist bitte...?", answer: "Where is...?" },
      {question: "Das ist ganz einfach.", answer: "That's very simple." },
      {question: "rechts", answer: "right" },
      {question: "links", answer: "left" },
      {question: "geradeaus", answer: "straight ahead" },
      {question: "Gehen Sie zuerst rechts und dann geradeaus", answer: "Go right first and then straight ahead." },
      {question: "richtig (Ist das richtig?)", answer: "correct (Is that correct?)" },
      {question: "genau (Ja, genau!)", answer: "exactly (Yes, exactly!)" },
      {question: "die Mitte", answer: "the middle/center" },
      {question: "Wo ist das? - Genau in der Mitte", answer: "Where is that? - Right in the middle" },
      {question: "also (Also, zuerst links und...)", answer: "so/therefore (So, first left and...)" },
      {question: "zeigen", answer: "to show/point" },
      {question: "der Plan", answer: "the map/plan" },
      {question: "zeichnen", answer: "to draw" },
      {question: "der Start", answer: "the start" },
      {question: "das Ziel", answer: "the destination" },
      {question: "schon (Da ist schon das Hotel.)", answer: "already (The hotel is already there.)" },
      {question: "Events", answer: "events" },
      {question: "das Event", answer: "the event" },
      {question: "das Festival", answer: "the festival" },
      {question: "das Ticket", answer: "the ticket" },
      {question: "das Publikum", answer: "the audience" },
      {question: "der Besucher", answer: "the visitor (male)" },
      {question: "die Besucherin", answer: "the visitor (female)" },
      {question: "der Gast", answer: "the guest" },
      {question: "das Konzert", answer: "the concert" },
      {question: "das Orchester", answer: "the orchestra" },
      {question: "der Chor", answer: "the choir" },
      {question: "die Konzertkarte", answer: "the concert ticket" },
      {question: "der Film", answer: "the film" },
      {question: "der Schauspieler", answer: "the actor (male)" },
      {question: "die Schauspielerin", answer: "the actor (female)" },
      {question: "der Star", answer: "the star" },
      {question: "der Regisseur", answer: "the director (male)" },
      {question: "die Regisseurin", answer: "the director (female)" },
      {question: "die Ausstellung", answer: "the exhibition" },
      {question: "finden", answer: "to find/to think" },
      {question: "Findest du das Konzert gut?", answer: "Do you think the concert is good?" },
      {question: "Jahreszeiten", answer: "seasons" },
      {question: "die Jahreszeit", answer: "the season" },
      {question: "der Frühling", answer: "spring" },
      {question: "der Sommer", answer: "summer" },
      {question: "der Herbst", answer: "autumn" },
      {question: "der Winter", answer: "winter" },
      {question: "Monate", answer: "months" },
      {question: "der Monat", answer: "the month" },
      {question: "der Januar", answer: "January" },
      {question: "der Februar", answer: "February" },
      {question: "der März", answer: "March" },
      {question: "der April", answer: "April" },
      {question: "der Mai", answer: "May" },
      {question: "der Juni", answer: "June" },
      {question: "der Juli", answer: "July" },
      {question: "der August", answer: "August" },
      {question: "der September", answer: "September" },
      {question: "der Oktober", answer: "October" },
      {question: "der November", answer: "November" },
      {question: "der Dezember", answer: "December" },
      {question: "die Gruppe", answer: "the group" },
      {question: "das Bild", answer: "the picture" },
      {question: "das Plakat", answer: "the poster" },
      {question: "das Glück", answer: "the luck/happiness" },
      {question: "so (So ein Glück!)", answer: "so (Such luck!)" },
      {question: "der Test", answer: "the test" },
      {question: "heute (Heute ist kein Test!)", answer: "today (There is no test today!)" },
      {question: "jetzt (Jetzt aber schnell!)", answer: "now (Now, quickly!)" },
      {question: "okay", answer: "okay" },
      {question: "die Welt", answer: "the world" },
      {question: "die Lösung", answer: "the solution" },
      {question: "ein Mal, zwei Mal, ...", answer: "one time, two times, ..." },
      {question: "das erste/zweite/... Mal", answer: "the first/second/... time" },
      {question: "Vielen Dank!", answer: "Thank you very much!" },
      {question: "der Park", answer: "the park" },
      {question: "der Markt", answer: "the market " },
      {question: "der Fluss", answer: "the river" },
      {question: "die Brücke", answer: "the bridge" },
      {question: "das Haus", answer: "the house " },
      {question: "das Glück", answer: "the luck/happiness" }
    ], 
    4:[
      {question: "das Haus", answer: "the house " },
      {question: "das Glück", answer: "the luck/happiness" }
    ],
    5: [
      {question: "das Haus", answer: "the house " },
      {question: "das Glück", answer: "the luck/happiness" }
    ]
    // ...add more Kapitel as needed
  },
  A2: {
    1: [
      { question: "Familie", answer: "The family" },
      { question: "geboren sein", answer: "to be born" },
      { question: "geschieden", answer: "divorced" },
      { question: "heiraten", answer: "to marry" },
      { question: "die Hochzeit", answer: "The wedding" },
      { question: "romantisch", answer: "romantic" },
      { question: "der Rentner", answer: "The male pensioner" },
      { question: "die Rentnerin", answer: "The female pensioner" },
      { question: "Beruf und Uni", answer: "Profession and university" },
      { question: "die Ausbildung", answer: "the training, education" },
      { question: "ab schließen", answer: "to complete/to finish" },
      { question: "beenden", answer: "to end, to finish" },
      { question: "die Arbeit", answer: "The work" },
      { question: "die Überstunde", answer: "The overtime hour" },
      { question: "der Augenoptiker", answer: "The optician (male)" },
      { question: "die Augenoptikerin", answer: "The optician (female)" },
      { question: "der Bankkaufmann, er", answer: "The banker (male)" },
      { question: "die Bankkauffrau", answer: "The banker (female)" },
      { question: "Biologie", answer: "Biology" },
      { question: "Mathematik", answer: "Mathematics" },
      { question: "die Note", answer: "The grade, the mark" },
      { question: "wohnen", answer: "to live/to reside" },
      { question: "mieten", answer: "to rent" },
      { question: "renovieren", answer: "to renovate" },
      { question: "das Stadtzentrum, Stadtzentren", answer: "The city center" },
      { question: "auf dem Land leben", answer: "to live in the countryside" },
      { question: "weiter suchen", answer: "to continue searching" },
      { question: "zusammen leben", answer: "to live together" },
      { question: "Freizeit", answer: "The free time/the leisure time" },
      { question: "vorschlagen", answer: "to suggest/to propose" },
      { question: "absagen", answer: "to cancel" },
      { question: "zusagen", answer: "to promise, accept, confirm" },
      { question: "einverstanden sein", answer: "to agree" },
      { question: "einen Plan ändern", answer: "to change a plan" },
      { question: "der Verein", answer: "The club, the association" },
      { question: "(sich) anmelden", answer: "to signin, Enroll, register" },
      { question: "teilnehmen", answer: "to take part, to participate" },
      { question: "gemeinsam", answer: "together, common" },
      { question: "organisieren", answer: "to organize" },
      { question: "der Flohmarkt", answer: "The flea market, farmer's market" },
      { question: "liegen", answer: "to lie/to be located" },
      { question: "das Pferd", answer: "The horse" },
      { question: "reiten", answer: "to ride" },
      { question: "spannend", answer: "exciting" },
      { question: "im Restaurant", answer: "in the restaurant" },
      { question: "der Aufenthalt", answer: "stay" },
      { question: "der Eingang", answer: "The entrance" },
      { question: "empfangen", answer: "to receive, to welcome" },
      { question: "der Platz", answer: "place, seat" },
      { question: "(sich) informieren (über + A.)", answer: "to inform (oneself) about" },
      { question: "auswählen", answer: "to choose/to select" },
      { question: "die Reservierung", answer: "The reservation" },
      { question: "spätestens", answer: "at the latest" },
      { question: "bitter", answer: "bitter" },
      { question: "salzig", answer: "salty" },
      { question: "sauer", answer: "sour" },
      { question: "scharf", answer: "spicy, hot" },
      { question: "das WC", answer: "The toilet, the restroom" },
      { question: "weiterhelfen", answer: "to help further" },
      { question: "aus sein", answer: "to be off" },
      { question: "die Zigarette", answer: "The cigarette" },
      { question: "mit allen Sinnen lernen", answer: "to learn with all the senses" },
      { question: "fühlen", answer: "to feel" },
      { question: "der Gegenstand", answer: "The object, the item" },
      { question: "der Sinn", answer: "The sense" },
      { question: "zuhören", answer: "to listen" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "die Angst", answer: "The fear" },
      { question: "die Grippe", answer: "The flu" },
      { question: "das Handy", answer: "The cell phone" },
      { question: "fast", answer: "almost" },
      { question: "also", answer: "so, therefore" },
      { question: "fließend", answer: "fluent" },
      { question: "eine Sprache fließend sprechen", answer: "to speak a language fluently" },
      { question: "begründen", answer: "to justify, to give reasons for" },
      { question: "rufen, er ruft, hat gerufen", answer: "to call" },
      { question: "ganz", answer: "whole, completely" },
      { question: "Mal sehen.", answer: "Let's see." },
      { question: "weil", answer: "because" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Ergänzen", answer: "to complete" },
      { question: "Früher habe ich im Stadtzentrum gewohnt.", answer: "I used to live in the city center." },
      { question: "Jetzt lebe ich mit meinem Freund zusammen.", answer: "Now I live together with my boyfriend." },
      { question: "Wir haben ein Haus auf dem Land gemietet.", answer: "We rented a house in the countryside." },
      { question: "Es ist sehr alt und wir haben es lange renoviert.", answer: "It is very old and we renovated it for a long time." },
      { question: "Ergänzen Sie je drei passende Wörter.", answer: "Add three suitable words each." },
      { question: "Familie", answer: "family" },
      { question: "der Bruder", answer: "The brother" },
      { question: "der Vater", answer: "the father" },
      { question: "die Schwester", answer: "the sister" },
      { question: "die Mutter", answer: "the mother" },
      { question: "Beruf", answer: "The profession/The job" },
      { question: "der Arzt", answer: "the doctor" },
      { question: "der Ingenieur", answer: "the engineer" },
      { question: "die Krankenschwester", answer: "the nurse" },
      { question: "die Kollegen", answer: "the colleagues" },
      { question: "wohnen", answer: "to live, to reside" },
      { question: "das Zimmer", answer: "the room" },
      { question: "der Balkon", answer: "the balcony" },
      { question: "das Apartment", answer: "the apartment" },
      { question: "das Fenster", answer: "the window" },
      { question: "Freizeit", answer: "Leisure time" },
      { question: "Freunde treffen", answer: "meet friends" },
      { question: "der Film", answer: "the film" },
      { question: "joggen", answer: "to jog" },
      { question: "das Spiel", answer: "the game" },
      { question: "Restaurant", answer: "restaurant" },
      { question: "die Rechnung", answer: "the bill" },
      { question: "der Kellner", answer: "the waiter" },
      { question: "die Bestellung", answer: "the order" },
      { question: "die Speisekarte", answer: "the menu" }
    ],
    2: [
      { question: "der Abschluss", answer: "the graduation/the degree/the qualification" },
      { question: "der Schulabschluss", answer: "the school leaving qualification, high school diploma" },
      { question: "das Abitur", answer: "German higher education  entrance qualification" },
      { question: "das Zeugnis", answer: "the report card/the certificate" },
      { question: "der Direktor", answer: "director (male)" },
      { question: "die Direktorin", answer: "director (female)" },
      { question: "der Schüler", answer: "student (male)" },
      { question: "die Schülerin", answer: "student (female)" },
      { question: "die Klasse", answer: "the class" },
      { question: "das Klassenzimmer", answer: "the classroom" },
      { question: "die Dauer", answer: "the duration" },
      { question: "die Unterrichtszeit", answer: "the class time/the teaching time" },
      { question: "der Stundenplan", answer: "the timetable/the schedule" },
      { question: "die Fremdsprache", answer: "the foreign language" },
      { question: "die Cafeteria, Cafeterien", answer: "the cafeteria, caferterias" },
      { question: "der Schulweg", answer: "the way to school/the school commute" },
      { question: "die Klassenfahrt", answer: "the class trip" },
      { question: "die Ferien", answer: "the holidays/the vacation" },
      { question: "die Schuluniform", answer: "the school uniform" },
      { question: "streng", answer: "strict" },
      { question: "die Vorbereitung", answer: "the preparation" },
      { question: "üben", answer: "to practice" },
      { question: "der Vokabeltest", answer: "the vocabulary test" },
      { question: "Schulfächer", answer: "School subjects" },
      { question: "das Fach", answer: "the school subject" },
      { question: "Lieblings", answer: "favorite" },
      { question: "Chemie", answer: "the chemistry" },
      { question: "Geografie", answer: "the geography" },
      { question: "Geschichte", answer: "the history" },
      { question: "Informatik", answer: "the computer science" },
      { question: "Latein", answer: "the Latin" },
      { question: "Kunsterziehung/Kunst", answer: "the art education/the art" },
      { question: "Mathematik/Mathe", answer: "the mathematics/the math" },
      { question: "Physik", answer: "the physics" },
      { question: "Sozialkunde", answer: "the social studies/the civics" },
      { question: "Wirschaft", answer: "Business" },
      { question: "die AG", answer: "type of company (stock corporation) or a school club (Arbeitsgemeinschaft)" },
      { question: "Schultypen", answer: "School types" },
      { question: "die Grundschule", answer: "the primary school" },
      { question: "die Hauptschule", answer: "type of secondary school" },
      { question: "die Realschule", answer: "type of secondary school" },
      { question: "das Gymnasium, Gymnasien", answer: "a type of secondary school leading to the Abitur" },
      { question: "die Gesamtschule", answer: "the comprehensive school" },
      { question: "die Berufsschule", answer: "the vocational school" },
      { question: "das Schulsystem", answer: "the school system" },
      { question: "das Bundesland", answer: "the federal state" },
      { question: "Berufe", answer: "Professions" },
      { question: "der Altenpfleger", answer: "geriatric nurse (male)" },
      { question: "die Arzthelferin", answer: "medical assistant (female)" },
      { question: "das Au-pair", answer: "the au pair" },
      { question: "der Englischlehrer", answer: "the English teacher (male)" },
      { question: "die Gärtnerin", answer: "the gardener (female)" },
      { question: "der Grafiker", answer: "the graphic designer (male)" },
      { question: "der Hotelkaufmann", answer: "the hotel manager (male)" },
      { question: "die Hotelkauffrau", answer: "the hotel manager (female)" },
      { question: "die Krankenschwester", answer: "the nurse (female)" },
      { question: "der Krankenpfleger", answer: "the nurse (male)" },
      { question: "Arbeit und Beruf", answer: "Work and Career" },
      { question: "die Arbeitswelt", answer: "the world of work" },
      { question: "der/die Auszubildende", answer: "the apprentice/the trainee" },
      { question: "der Azubi", answer: "the trainee/the apprentice (Informal)" },
      { question: "die Lehre", answer: "the apprenticeship" },
      { question: "die Berufserfahrung", answer: "the professional experience/the work experience" },
      { question: "die Erfahrung", answer: "the experience" },
      { question: "das Berufsleben", answer: "the working life/the professional life" },
      { question: "das Handwerk", answer: "to skilled trade/the craft" },
      { question: "jobben", answer: "to work (casual/side job/to temp)" },
      { question: "die Messe", answer: "the trade fair/the exhibition" },
      { question: "die Arztpraxis, Arztpraxen", answer: "the doctor's office/the doctor's offices" },
      { question: "das Reisebüro", answer: "the travel agency" },
      { question: "die Werbeagentur", answer: "the advertising agency" },
      { question: "Universität", answer: "University" },
      { question: "Jura (Sie hat Jura studiert.)", answer: "the law (She studied law.)" },
      { question: "Medizin", answer: "the medicine" },
      { question: "die Vorlesung", answer: "the lecture" },
      { question: "eine Vorlesung besuchen", answer: "to attend a lecture" },
      { question: "die Meinung sagen", answer: "express your opinion" },
      { question: "die Meinung", answer: "the opinion" },
      { question: "ablehnen", answer: "to reject/to decline" },
      { question: "zustimmen", answer: "to agree, to consent" },
      { question: "nützlich", answer: "useful" },
      { question: "witzig", answer: "funny/witty" },
      { question: "furchtbar", answer: "terrible/awful" },
      { question: "schlecht", answer: "bad" },
      { question: "wütend", answer: "furious/angry" },
      { question: "Das sehe ich anders.", answer: "I see that differently." },
      { question: "Das war bei mir auch so.", answer: "That was the same for me too." },
      { question: "die Hauptsache", answer: "the main thing " },
      { question: "überraschen", answer: "to surprise" },
      { question: "überrascht sein", answer: "to be surprised" },
      { question: "die Gemeinsamkeit", answer: "the commonality/the similarity" },
      { question: "der Unterschied", answer: "the difference" },
      { question: "wahrscheinlich", answer: "probably" },
      { question: "wenigstens", answer: "at least" },
      { question: "ziemlich", answer: "quite/pretty" },
      { question: "zum Beispiel", answer: "for example" },
      { question: "andere wichtige Wörter und Wendungen", answer: "other important words and phrases" },
      { question: "aus|schlafen, er schläft aus, hat ausgeschlafen", answer: "to sleep in, he sleeps in, has slept in" },
      { question: "die Behinderung", answer: "the disability" },
      { question: "der Rollstuhl", answer: "the wheelchair" },
      { question: "ehrlich", answer: "honest/honestly" },
      { question: "die Erholung", answer: "the recovery/the relaxation" },
      { question: "die Erinnerung", answer: "the memory" },
      { question: "die Weltreise", answer: "the world trip/the world tour" },
      { question: "erwachsen", answer: "adult/grown-up" },
      { question: "unabhängig", answer: "independent" },
      { question: "freiwillig", answer: "voluntary" },
      { question: "sozial", answer: "social" },
      { question: "die Grafik", answer: "the graphic/the chart (see the graphic." },
      { question: "heute", answer: "today" },
      { question: "erst mal", answer: "first/for now" },
      { question: "paar", answer: "a few/couple" },
      { question: "der Kontakt", answer: "the contact" },
      { question: "verlieren", answer: "to lose" },
      { question: "je", answer: "each, respectively" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Ergänzen Sie Wörter.", answer: "Complete word" },
      { question: "Sozialkunde", answer: "Social Studies" },
      { question: "Chemie", answer: "Chemistry" },
      { question: "Hauptschule", answer: "Secondary School" },
      { question: "Universität", answer: "University" },
      { question: "Latin", answer: "Latin" },
      { question: "Erwachsen", answer: "Adult" },
      { question: "Bundesland", answer: "Federal State" },
      { question: "Erfahrung", answer: "Experience" },
      { question: "Reisebüro", answer: "Travel Agency" },
      { question: "Hotelkaufmann", answer: "Hotel Manager (male)" },
      { question: "Fremdsprache", answer: "Foreign Language" },
      { question: "Ehrlich", answer: "Honest" },
      { question: "Arztpraxis", answer: "Doctor's Office" },
      { question: "Realschule", answer: "Secondary School" },
      { question: "Berufsschule", answer: "Vocational School" },
      { question: "Erst mal", answer: "First of all" },
      { question: "Informatik", answer: "Computer Science" },
      { question: "Typ", answer: "Type" }
    ],
    3: [
      { question: "Medien und Geräte", answer: "The media and devices" },
      { question: "das E-Book", answer: "The e-book" },
      { question: "der E-Book-Reader", answer: "The e-book reader" },
      { question: "der Laptop", answer: "The laptop" },
      { question: "das Radio", answer: "The radio" },
      { question: "das Smartphone", answer: "The smartphone" },
      { question: "die Spielekonsole", answer: "The games console" },
      { question: "das Tablet", answer: "The tablet" },
      { question: "der Bildschirm", answer: "The screen/monitor" },
      { question: "die Tastatur", answer: "The keyboard" },
      { question: "die Maus", answer: "The mouse" },
      { question: "das Kabel", answer: "The cable" },
      { question: "der Lautsprecher", answer: "The loudspeaker/speaker" },
      { question: "die Webseite", answer: "The website" },
      { question: "der Link", answer: "The link" },
      { question: "der Kontakt", answer: "The contact" },
      { question: "in Kontakt bleiben", answer: "To stay in contact" },
      { question: "Aktivitäten mit Medien", answer: "Activities with media" },
      { question: "an sein", answer: "To be on" },
      { question: "an klicken", answer: "To click (on)" },
      { question: "tippen", answer: "To type" },
      { question: "checken", answer: "To check" },
      { question: "downloaden", answer: "To download" },
      { question: "herunterladen", answer: "To download" },
      { question: "hoch laden", answer: "To upload" },
      { question: "kopieren", answer: "To copy" },
      { question: "löschen", answer: "To delete" },
      { question: "mailen", answer: "To email" },
      { question: "senden", answer: "To send" },
      { question: "weiter leiten", answer: "To forward" },
      { question: "bloggen", answer: "To blog" },
      { question: "der Blogbeitrag", answer: "The blog post" },
      { question: "chatten", answer: "To chat" },
      { question: "posten", answer: "To post" },
      { question: "teilen", answer: "To share" },
      { question: "Fotos teilen", answer: "To share photos" },
      { question: "Dinge vergleichen", answer: "To compare things" },
      { question: "der Vergleich", answer: "The comparison" },
      { question: "leicht", answer: "light, easy" },
      { question: "als", answer: "than" },
      { question: "wie", answer: "as" },
      { question: "genauso", answer: "just as/equally" },
      { question: "über Arbeit sprechen", answer: "To talk about work" },
      { question: "das Start-Up", answer: "The start-up" },
      { question: "gründen", answer: "To found/to start" },
      { question: "ein Start-Up gründen", answer: "To found a start-up" },
      { question: "der/die Studierende", answer: "The student (male/female)" },
      { question: "entwickeln (eine App entwickeln)", answer: "To develop (To develop an app)" },
      { question: "programmieren", answer: "To program" },
      { question: "Meinung äußern", answer: "To express an opinion" },
      { question: "die Umfrage", answer: "The survey" },
      { question: "kommentieren", answer: "To comment" },
      { question: "meinen", answer: "To mean/think" },
      { question: "mit teilen", answer: "To inform/communicate/to share" },
      { question: "kritisch", answer: "critical" },
      { question: "blöd", answer: "stupid/silly" },
      { question: "peinlich", answer: "embarrassing" },
      { question: "privat", answer: "private" },
      { question: "dass", answer: "that" },
      { question: "Kino und Filme", answer: "Cinema and films/movies" },
      { question: "der Actionfilm", answer: "The action film/movie" },
      { question: "der Fantasy-Film", answer: "The fantasy film/movie" },
      { question: "die Komödie", answer: "The comedy" },
      { question: "der Krimi", answer: "The crime film/mystery" },
      { question: "der Liebesfilm", answer: "The romance film/love story" },
      { question: "der Thriller", answer: "The thriller" },
      { question: "die Filmmusik", answer: "The film music/soundtrack" },
      { question: "die Handlung", answer: "The plot/action/story" },
      { question: "Worum geht es im Film?", answer: "What is the film about?" },
      { question: "der Trailer", answer: "The trailer" },
      { question: "die Hauptperson", answer: "The main character" },
      { question: "das Talent", answer: "The talent" },
      { question: "der Humor", answer: "The humor" },
      { question: "der Witz", answer: "The joke" },
      { question: "spielen", answer: "To play/to be set" },
      { question: "einfach", answer: "just/simply" },
      { question: "logisch", answer: "logical" },
      { question: "real", answer: "real" },
      { question: "andere wichtige Wörter und Wendungen", answer: "Other important words and phrases" },
      { question: "aus probieren", answer: "To try out/test out" },
      { question: "gewinnen", answer: "To win" },
      { question: "lachen", answer: "To laugh" },
      { question: "weinen", answer: "To cry" },
      { question: "flüstern", answer: "To whisper" },
      { question: "dumm, dümmer, am dümmsten", answer: "stupid, more stupid, most stupid" },
      { question: "fröhlich", answer: "cheerful/happy" },
      { question: "nah, näher, am nächsten", answer: "near, nearer, nearest" },
      { question: "schwierig", answer: "difficult/hard" },
      { question: "still", answer: "quiet/still" },
      { question: "vorsichtig", answer: "careful" },
      { question: "der Enkel", answer: "The grandson" },
      { question: "die Enkelin", answer: "The granddaughter" },
      { question: "die Freundschaft", answer: "The friendship" },
      { question: "die Kindheit", answer: "The childhood" },
      { question: "das Schicksal", answer: "The fate/destiny" },
      { question: "die Sorge", answer: "The worry" },
      { question: "sterben", answer: "To die" },
      { question: "tot", answer: "dead" },
      { question: "das Tier", answer: "The animal" },
      { question: "manche, mancher", answer: "some/some people" },
      { question: "mehrmals", answer: "several times" },
      { question: "plötzlich", answer: "suddenly" },
      { question: "überhaupt", answer: "at all" },
      { question: "unbedingt", answer: "absolutely/definitely" },
      { question: "zuletzt", answer: "lastly/finally/most recently" },
      { question: "Wichtig für mich:", answer: "Important for me:" },
      { question: "Welche Filme gibt es? Ergänzen Sie die Buchstaben.", answer: "Which films are there? Fill in the letters." },
      { question: "die Komödie", answer: "The comedy" },
      { question: "der Thriller", answer: "The thriller" },
      { question: "der Actionfilm", answer: "The action film/movie" },
      { question: "der Krimi", answer: "The crime film/mystery" },
      { question: "der Fantasy-Film", answer: "The fantasy film/movie" },
      { question: "der Liebesfilm", answer: "The romance film/love story" },
      { question: "Was kann man damit machen? Notieren Sie möglichst viele Verben.", answer: "What can you do with that? Note as many verbs as possible." },
      { question: "die Mail", answer: "The email" },
      { question: "checken", answer: "to check" },
      { question: "senden", answer: "to send" },
      { question: "mailen", answer: "to email" },
      { question: "weiterleiten", answer: "to forward" },
      { question: "löschen", answer: "to delete" },
      { question: "kopieren", answer: "to copy" },
      { question: "die App", answer: "The app" },
      { question: "entwickeln", answer: "to develop" },
      { question: "downloaden", answer: "to download" },
      { question: "herunterladen", answer: "to download" },
      { question: "hochladen", answer: "to upload" },
      { question: "das Foto", answer: "The photo" },
      { question: "teilen", answer: "to share" },
      { question: "löschen", answer: "to delete" },
      { question: "kopieren", answer: "to copy" },
      { question: "hochladen", answer: "to upload" },
      { question: "das Smartphone", answer: "The smartphone" },
      { question: "tippen", answer: "to type" },
      { question: "chatten", answer: "to chat" },
      { question: "an sein", answer: "to be on" },
      { question: "downloaden", answer: "to download" },
      { question: "herunterladen", answer: "to download" },
      { question: "telefonieren", answer: "to make a phone call - implied" },
      { question: "surfen", answer: "to surf the web - implied" }
      ]
  },
  B1: {
    1: [
      { question: "Familie", answer: "family" },
      { question: "geboren sein", answer: "to be born" },
      { question: "geschieden", answer: "divorced" },
      { question: "heiraten", answer: "to marry" },
      { question: "die Hochzeit", answer: "the Wedding" },
      { question: "romantisch", answer: "romantic" },
      { question: "der Rentner", answer: "the pensioner (male)" },
      { question: "die Rentnerin", answer: "the pensioner (female)" },
      { question: "Beruf unf Uni", answer: "Career and University" },
      { question: "die Ausbildung", answer: "the training" },
      { question: "die Arbeit", answer: "the Work" },
      { question: "die überstunde", answer: "the overtime hours" },
      { question: "der Augenoptiker", answer: "the optician (male)" },
      { question: "die Augenoptikerin", answer: "the optician (female)" },
      { question: "der Bankkaufmann", answer: "the banker (male)" },
      { question: "die Bankkauffrau", answer: "the banker (female)" },
      { question: "Biologie", answer: "Biology" },
      { question: "Mathematik/Mathe", answer: "Mathematics" },
      { question: "wohnen", answer: "to live, to reside" },
      { question: "mieten", answer: "to rent" },
      { question: "renovieren", answer: "to renovate" },
      { question: "das Stadtzentrum", answer: "the city center" },
      { question: "auf dem Land leben", answer: "to live in countryside" },
      { question: "weiter suchen", answer: "continue searching" },
      { question: "zusammen leben", answer: "to live together" },
      { question: "Freizeit", answer: "Leisure time, free time" },
      { question: "vorschlagen", answer: "to suggest, to propose" },
      { question: "absagen", answer: "to cancel" },
      { question: "zusagen", answer: "to promise, to accept, to confirm" },
      { question: "einen Plan ändern", answer: "to change the plan" },
      { question: "anmelden", answer: "signin, enroll, register" },
      { question: "teilnehmen", answer: "to take part, to participate" },
      { question: "gemeinsam", answer: "together, common" },
      { question: "organisieren", answer: "to organize" },
      { question: "der Flohmarkt", answer: "flea market, farmer's market" },
      { question: "liegen", answer: "to lie, to be locate" },
      { question: "das Pferd", answer: "the horse" },
      { question: "reiten", answer: "to ride" },
      { question: "spannend", answer: "exciting" },
      { question: "Im Restaurant", answer: "in the Restaurant" },
      { question: "der Aufenthalt", answer: "stay" },
      { question: "der Eingang", answer: "entrance" },
      { question: "empfangen", answer: "to receive, to welcome" },
      { question: "der Platz", answer: "seat, place" },
      { question: "sich informieren", answer: "to inform oneself" },
      { question: "auswählen", answer: "to choose, to select" },
      { question: "die Reservierung", answer: "reservation" },
      { question: "spätestens", answer: "at the latest" },
      { question: "bitter", answer: "bitter" },
      { question: "salzig", answer: "salty" },
      { question: "sauer", answer: "sour" },
      { question: "scharf", answer: "spicy, hot" },
      { question: "das WC", answer: "washroom, toilet" },
      { question: "weiter helfen", answer: "to help further" },
      { question: "die Zigarette", answer: "the cigarette" },
      { question: "fühlen", answer: "to feel" },
      { question: "der sinn", answer: "sense" },
      { question: "zuhören", answer: "to listen" },
      { question: "die Angst", answer: "the fear" },
      { question: "die Grippe", answer: "the flu" },
      { question: "das Handy", answer: "the mobile phone" },
      { question: "fast", answer: "almost" },
      { question: "also", answer: "so, therefore" },
      { question: "Fließend", answer: "fluent" },
      { question: "Eine Sprache fließend sprechen", answer: "to speak a language fluently" },
      { question: "rufen", answer: "to call" },
      { question: "ganz", answer: "entire, complete" },
      { question: "Mal sehen", answer: "Let's see" },
      { question: "weil", answer: "because" },
      { question: "zusammen", answer: "together" },
      { question: "leben", answer: "to live" },
      { question: "alt", answer: "old" },
      { question: "lange", answer: "long" },
      { question: "land", answer: "country" },
      { question: "wichtig", answer: "important" },
      { question: "ergänzen", answer: "to complete" },
      { question: "der Bruder", answer: "the brother" },
      { question: "die Schwester", answer: "the sister" },
      { question: "der Vater", answer: "the father" },
      { question: "die Mutter", answer: "the mother" },
      { question: "der Arzt", answer: "the doctor" },
      { question: "der Ingenieur", answer: "the engineer" },
      { question: "die Kollegen", answer: "the colleagues" },
      { question: "die Krankenschwester", answer: "the nurse" },
      { question: "das Zimmer", answer: "the room" },
      { question: "das Apartment", answer: "the apartment" },
      { question: "der Balkon", answer: "the balcony" },
      { question: "das Fenster", answer: "the window" },
      { question: "Freunde treffen", answer: "Meeting friends" },
      { question: "joggen", answer: "to jog, jogging" },
      { question: "das Spiel", answer: "the game" },
      { question: "der Film", answer: "the movie, the film" },
      { question: "die Rechnung", answer: "the bill" },
      { question: "der Kellner", answer: "the waiter" },
      { question: "die Bestellung", answer: "the order" },
      { question: "die Speisekarte", answer: "the menu" },
      { question: "Schule", answer: "school" },
      { question: "der Abschluss", answer: "the degree, graduation" },
      { question: "der Schulabschluss", answer: "School leaving certificate" },
      { question: "das Abitur", answer: "German Higher education degree/certificate" },
      { question: "der Direktor", answer: "the Director (male)" },
      { question: "die Direktorin", answer: "the Director (female)" },
      { question: "der Schüler", answer: "the student (male)" },
      { question: "die Schülerin", answer: "the student (female)" },
      { question: "die Klasse", answer: "the class" },
      { question: "das Klassenzimmer", answer: "the classroom" },
      { question: "die Dauer", answer: "the duration" },
      { question: "die Unterrichtszeit", answer: "the classroom time" },
      { question: "der Studentplan", answer: "the time table, the schedule" },
      { question: "die Fremdsprache", answer: "the foreign language" },
      { question: "die Caferia", answer: "the cafeteria" },
      { question: "der Schulweg", answer: "the way of school" },
      { question: "die Klassenfahrt", answer: "the class trip" },
      { question: "die Ferien", answer: "holidays, vacation" },
      { question: "die Schuluniform", answer: "the school uniform" },
      { question: "streng", answer: "strict" },
      { question: "die Vorbereitung", answer: "preparation" },
      { question: "üben", answer: "to practice" },
      { question: "der Vokabeltest", answer: "the vocabulary test" },
      { question: "das Fach", answer: "the subject" },
      { question: "Lieblings", answer: "favourite " },
      { question: "Chemie", answer: "chemistry" },
      { question: "Geografie", answer: "geography" },
      { question: "Geschicte", answer: "history" },
      { question: "Infomatik", answer: "computer science" },
      { question: "Latin", answer: "lation" },
      { question: "Physik", answer: "Physics" },
      { question: "Sozialkunde", answer: "social studies" },
      { question: "Wirtschaft", answer: "Business" },
      { question: "Schultypen", answer: "types of school" },
      { question: "die Grundschule", answer: "primary school" },
      { question: "die Hauptschule", answer: "types of secondary school" },
      { question: "die Realschule", answer: "types of secondary school" },
      { question: "das Gymnasium", answer: "types of secondary school" },
      { question: "die Gesamtschule", answer: "comprehensive school" },
      { question: "die Berufsschule", answer: "vocational school" },
      { question: "das Schulsystem", answer: "school system" },
      { question: "das Bundesland", answer: "federal state" },
      { question: "Berufe", answer: "professions" },
      { question: "der Altenpfleger", answer: "the nurse (male)" },
      { question: "der EnglischLehrer", answer: "the english teacher" },
      { question: "die Gärtnerin", answer: "gardener (female)" },
      { question: "die Grafiker", answer: "the graphic designer (male)" },
      { question: "der Hotelkaufmann", answer: "the hotel manager (male)" },
      { question: "die Hotelkauffrau", answer: "the hotel manager (female)" },
      { question: "die Krankenschwester", answer: "the nurse (female)" },
      { question: "der Krankenpfleger", answer: "the nurse (male)" },
      { question: "Arbeit und Beruf", answer: "work and career" },
      { question: "die Arbeitswelt", answer: "the world of work" },
      { question: "der Azubi", answer: "the trainee" },
      { question: "die Berufserfahrung", answer: "the professional experience" },
      { question: "die Erfahrung", answer: "the experience" },
      { question: "das Berufsleben", answer: "the working life" },
      { question: "Das Handwerk", answer: "the handwork, craft work" },
      { question: "jobben", answer: "to work (casual, side job, temp job)" },
      { question: "die Arztpraxis", answer: "the doctor's office" },
      { question: "das Reisebüro", answer: "the travel agency" },
      { question: "die Werbeagentur", answer: "the advertising agency" },
      { question: "Universität", answer: "University" },
      { question: "der Jura", answer: "the law" },
      { question: "der Medizine", answer: "the Medicine" },
      { question: "die Meinung sagen", answer: "express your opinion" },
      { question: "die Meinung", answer: "the opinion" },
      { question: "zustimmen", answer: "to agree, to consent" },
      { question: "nützlich", answer: "useful" },
      { question: "witzig", answer: "funny, witty" },
      { question: "furchtbar", answer: "terrible, awful" },
      { question: "schlecht", answer: "bad" },
      { question: "wütend", answer: "furious, angry" },
      { question: "Das sehe ich anders", answer: "I see it differently." },
      { question: "Das war bei mir auch so.", answer: "it was the same for me." },
      { question: "überraschen", answer: "the surprise" },
      { question: "überrascht sein", answer: "to be surprised" },
      { question: "die Gemeinsamkeit", answer: "similarity, commonality" },
      { question: "wahrscheinlich", answer: "probably" },
      { question: "wenigstens", answer: "at least" },
      { question: "zum Beispiel", answer: "for example" },
      { question: "der Rohrstuhl", answer: "the wheelchair" },
      { question: "ehrlich", answer: "honestly" },
      { question: "die Erinnerung", answer: "memory" },
      { question: "die Weltreise", answer: "worldtrip" },
      { question: "erwachsen", answer: "adult, grown up" },
      { question: "sozial", answer: "social" },
      { question: "die Grafik", answer: "the graphic, the chart" },
      { question: "heute", answer: "today" },
      { question: "erst mal", answer: "first of all" },
      { question: "paar", answer: "a couple of, a few" },
      { question: "der Kontakt", answer: "contact" },
      { question: "verlieren", answer: "to lose" },
      { question: "Media und Geräte", answer: "media and devices" },
      { question: "das E-Book", answer: "the e-book" },
      { question: "der E-Book-Reader", answer: "the E-Book-Reader" },
      { question: "der Laptop", answer: "the laptop" },
      { question: "das Radio", answer: "the radio" },
      { question: "das Smartphone", answer: "the smartphone" },
      { question: "die Spielekonsole", answer: "the games console" },
      { question: "das Tablet", answer: "the tablet" },
      { question: "die Bildschrim", answer: "the screen, the monitor (computer)" },
      { question: "die Tastatur", answer: "the keyboard" },
      { question: "die Maus", answer: "the mouse" },
      { question: "das Kabel", answer: "the cable" },
      { question: "der Lautsprecher", answer: "the loudspeaker" },
      { question: "die Webseite", answer: "the website" },
      { question: "der Link", answer: "the link" },
      { question: "der Kontakt", answer: "the contact" },
      { question: "in Kontakt bleiben", answer: "to stay in contact" },
      { question: "Aktivitäten mit Medien", answer: "Activities with media" },
      { question: "anklicken", answer: "to click on" },
      { question: "tippen", answer: "to type" },
      { question: "checken", answer: "to check" },
      { question: "downloaden", answer: "to download" },
      { question: "herunterladen", answer: "to download" },
      { question: "hochladen", answer: "to upload" },
      { question: "kopieren", answer: "to copy" },
      { question: "löschen", answer: "to delete" },
      { question: "mailen", answer: "to email" },
      { question: "senden", answer: "to send" },
      { question: "weiterleiten", answer: "to forward" },
      { question: "bloggen", answer: "to blog" },
      { question: "chatten", answer: "to chat" },
      { question: "posten", answer: "to post" },
      { question: "teilen", answer: "to share" },
      { question: "Fotos teilen", answer: "to share photos" },
      { question: "Dinge vergleichen", answer: "Comparing things" },
      { question: "der Vergleich", answer: "the comparison" },
      { question: "leicht", answer: "light, easy" },
      { question: "als", answer: "than" },
      { question: "wie", answer: "as" },
      { question: "genauso", answer: "just as" },
      { question: "über Arbeit sprechen", answer: "talk about work" },
      { question: "das Start up", answer: "the start up" },
      { question: "entwickeln", answer: "to develop" },
      { question: "programmieren", answer: "to program" },
      { question: "die Umfrage", answer: "the survey" },
      { question: "kommentieren", answer: "to comment" },
      { question: "kritisch", answer: "critical" },
      { question: "blöd", answer: "stupid" },
      { question: "peinlich", answer: "embarrassing" },
      { question: "privat", answer: "private" },
      { question: "dass", answer: "that" },
      { question: "Kino und Filme", answer: "cinema and films" },
      { question: "der Actionfilm", answer: "the action film" },
      { question: "der Fantasy Film", answer: "the fantasy film" },
      { question: "die Komödie", answer: "the comedy" },
      { question: "der Krimi", answer: "the crime film" },
      { question: "der Liebesfilm", answer: "the Romance film" },
      { question: "der Thriller", answer: "the thriller" },
      { question: "die Filmmusik", answer: "film music" },
      { question: "die Handlung", answer: "the plot, the story" },
      { question: "Worum geht es im Film?", answer: "What is the film about?" },
      { question: "der Trailer", answer: "the trailer" },
      { question: "die Hauptperson", answer: "main character" },
      { question: "das Talent", answer: "the talent" },
      { question: "der Humor", answer: "the humor" },
      { question: "der Witz", answer: "joke" },
      { question: "spielen", answer: "to play" },
      { question: "einfach", answer: "simple" },
      { question: "logisch", answer: "logical" },
      { question: "real", answer: "real" },
      { question: "ausprobieren", answer: "to try out" },
      { question: "gewinnen", answer: "to win" },
      { question: "lachen", answer: "to laugh" },
      { question: "weinen", answer: "to cry" },
      { question: "flüstern", answer: "to whisper" },
      { question: "dumm, dümmer, am dümmsten", answer: "stupid, more stupid, most stupid" },
      { question: "fröhlich", answer: "cheerful, happy" },
      { question: "Nah, näher, am nächsten", answer: "near, nearer, nearest" },
      { question: "schwierig", answer: "difficult" },
      { question: "der Enkel", answer: "grandson" },
      { question: "die Enkelin", answer: "granddaugther" },
      { question: "die Freundschaft", answer: "friendship" },
      { question: "die Kinderheit", answer: "the childhood" },
      { question: "die Sorge", answer: "worry, concern" },
      { question: "sterben", answer: "to die" },
      { question: "das Tier", answer: "the animal" },
      { question: "manche", answer: "some, a few" },
      { question: "einige", answer: "some, a few" },
      { question: "mehrmals", answer: "several times" },
      { question: "Plötzlich", answer: "suddenly" },
      { question: "zuletzt", answer: "last, finally" },
      { question: "die App", answer: "the app" },
      { question: "das Foto", answer: "the photo" },
      { question: "das Smartphone", answer: "the smartphone" },
      { question: "telefonieren", answer: "to make a phone call" },
      { question: "die Geburt", answer: "the birth" },
      { question: "die Geburtstagsparty", answer: "the birthday party" },
      { question: "der Schultag", answer: "the school day" },
      { question: "der Führerschein", answer: "driving license" },
      { question: "die Führerscheinprüfung", answer: "the driving test" },
      { question: "der Club", answer: "the club" },
      { question: "das brautpaar", answer: "bridal couple" },
      { question: "der Ring", answer: "the ring" },
      { question: "platz", answer: "place" },
      { question: "die Medaille", answer: "the medal" },
      { question: "das Feuerwerk", answer: "the fireworks" },
      { question: "die Karte", answer: "the card" },
      { question: "gratulieren", answer: "to congratulate" },
      { question: "wie", answer: "how" },
      { question: "Alles Gute", answer: "All the best" },
      { question: "sich bedanken", answer: "to thank someone " },
      { question: "tausend Dank", answer: "thousand thanks" },
      { question: "die Absage", answer: "rejection" },
      { question: "stehen", answer: "to stand" },
      { question: "das Gefühl", answer: "feeling" },
      { question: "die Emotion", answer: "the emotion" },
      { question: "Angst haben", answer: "to be afraid" },
      { question: "keine Ahnung haben", answer: "to have no idea" },
      { question: "die Laune", answer: "the mood" },
      { question: "die Liebe", answer: "the love" },
      { question: "Das ist ja toll", answer: "That’s great" },
      { question: "So ein Glück", answer: "What luck!" },
      { question: "sich ärgern", answer: "to get angry" },
      { question: "sich streiten", answer: "to argue" },
      { question: "Das tut mir (Wirklich) leid", answer: "I’m really sorry" },
      { question: "schade", answer: "too bad" },
      { question: "Das macht (doch) nichts", answer: "it doesn’t matter." },
      { question: "Es geht schon wieder", answer: "it’s okay again" },
      { question: "Es ist alles okay", answer: "Everything is okay" },
      { question: "hoffen", answer: "to hope" },
      { question: "genervt", answer: "annoyed" },
      { question: "gestresst", answer: "stressed" },
      { question: "nervös", answer: "nervous" },
      { question: "sauer", answer: "angry" },
      { question: "stolz", answer: "proud" },
      { question: "traurig", answer: "sad" },
      { question: "unglücklich", answer: "unhappy" },
      { question: "sich erinnern", answer: "to remember" },
      { question: "sich gewöhnen", answer: "to get used" },
      { question: "sich austauschen", answer: "to exchange ideas" },
      { question: "fallen", answer: "to fall" },
      { question: "anbieten", answer: "to offer" },
      { question: "sich ausruhen", answer: "to rest" },
      { question: "unterrichten", answer: "to teach" },
      { question: "wegfahren", answer: "to drive away" },
      { question: "außerdem", answer: "besides, furthermore " },
      { question: "inzwischen", answer: "meanwhile, in between" },
      { question: "das Frühjahr", answer: "spring" },
      { question: "die zukunft", answer: "the future" },
      { question: "das Gegenteil", answer: "the opposite" },
      { question: "der Verkehr", answer: "the traffic" },
      { question: "verspätet", answer: "delayed, late" },
      { question: "kostenlos", answer: "free of charge" },
      { question: "niemand", answer: "nobody" },
      { question: "nirgends", answer: "nowhere" },
      { question: "fremd", answer: "foreign, strange" },
      { question: "hilfsbereit", answer: "helpful" },
      { question: "wahr", answer: "true" },
      { question: "weltweit", answer: "worldwide" },
      { question: "Wenn…dann…", answer: "if…then…" },
      { question: "Verkehr in der Stadt", answer: "traffic in the city" },
      { question: "das E bike", answer: "the E bike" },
      { question: "flexibel", answer: "flexible" },
      { question: "die Linie", answer: "the line" },
      { question: "der Radfahrer", answer: "the cyclist" },
      { question: "der Radweg", answer: "the bike path" },
      { question: "die Seibahn", answer: "the cable car" },
      { question: "Verkehrsprobleme", answer: "traffic problems" },
      { question: "der Stau", answer: "the traffic jam" },
      { question: "die Luft", answer: "the air" },
      { question: "in zukunft", answer: "in the future" },
      { question: "reduzieren", answer: "to reduce" },
      { question: "die Großstadt", answer: "the big city" },
      { question: "die Innenstadt", answer: "the inner city" },
      { question: "die Kombination", answer: "the combination" },
      { question: "die Konsequenz", answer: "the consequence" },
      { question: "das Konzept", answer: "the concept" },
      { question: "rund ums Auto", answer: "All about the car" },
      { question: "das kennzeichen", answer: "the license plate" },
      { question: "der Motor", answer: "the engine" },
      { question: "der Reifen", answer: "the tire" },
      { question: "bremsen", answer: "to brake" },
      { question: "die Garage", answer: "the garage" },
      { question: "das Navi", answer: "the navigation system" },
      { question: "der Diesel", answer: "the diesel" },
      { question: "tanken", answer: "the refuel" },
      { question: "die Tankstelle", answer: "the gas station" },
      { question: "parken", answer: "to park" },
      { question: "das Parkhaus", answer: "the parking garage" },
      { question: "der Parkplatz", answer: "the parking space" },
      { question: "im Zug", answer: "On the train" },
      { question: "die Zugfahrt", answer: "the train journey" },
      { question: "das Bordbistro", answer: "the train café" },
      { question: "das Kinderabteil", answer: "the children's compartment" },
      { question: "die Monatskarte", answer: "the monthly pass" },
      { question: "die Platzreservierung", answer: "the seat reservation" },
      { question: "brauchen", answer: "to need " },
      { question: "weiter fahren", answer: "to drive on/to continue " },
      { question: "der Abflug", answer: "the departure" },
      { question: "buchen", answer: "to book" },
      { question: "landen", answer: "to land" },
      { question: "einen Weg beschreiben", answer: "to describe a path" },
      { question: "gegenüber von (+D.)", answer: "opposite of (+ Dative)" },
      { question: "vorwärts", answer: "forwards" },
      { question: "rückwärts", answer: "backwards" },
      { question: "Geh immer geradeaus.", answer: "Always go straight ahead." },
      { question: "die Ampel", answer: "the traffic light" },
      { question: "halten", answer: "to stop/to hold" },
      { question: "einen Service nutzen", answer: "to use a service" },
      { question: "der Kundenservice", answer: "the customer service" },
      { question: "telefonisch", answer: "by telephone" },
      { question: "erreichen", answer: "to reach" },
      { question: "lösen", answer: "to solve" },
      { question: "registrieren (sich)", answer: "to register (oneself)" },
      { question: "die PIN", answer: "the PIN" },
      { question: "die Expertin", answer: "the expert (female)" },
      { question: "das Prozent", answer: "the percent" },
      { question: "etwa", answer: "about, approximately" },
      { question: "zeigen", answer: "to show" },
      { question: "die Meinung sagen", answer: "to give one's opinion" },
      { question: "die Meinung", answer: "the opinion" },
      { question: "Du hast recht.", answer: "You are right." },
      { question: "gegen + Akkusativ", answer: "against" },
      { question: "der Artikel", answer: "the article" },
      { question: "der Kinderwagen", answer: "the stroller" },
      { question: "die Mama", answer: "the mom, the mummy" },
      { question: "die Stadtbesichtigung", answer: "the city tour" },
      { question: "der Konzertsaal", answer: "the concert hall" },
      { question: "klatschen", answer: "to clap" },
      { question: "die Kaution", answer: "the deposit" },
      { question: "ob", answer: "if, whether" },
      { question: "schon mal", answer: "already, ever" },
      { question: "die SMS", answer: "the text message" },
      { question: "die Werbung", answer: "the advertisement" },
      { question: "elektrisch", answer: "electric" },
      { question: "ewig", answer: "forever" },
      { question: "nervig", answer: "annoying, irritating" },
      { question: "nötig", answer: "necessary" },
      { question: "sinnvoll", answer: "sensible" },
      { question: "unpraktisch", answer: "impractical" },
      { question: "setzen (sich)", answer: "to sit down" },
      { question: "überlegen (sich)", answer: "to consider (oneself)" },
      { question: "versprechen", answer: "to promise" },
      { question: "den Bus", answer: "the bus" },
      { question: "mit dem Zug", answer: "by train" },
      { question: "zu Fuß", answer: "on foot" },
      { question: "im Stau", answer: "in the traffic jam" },
      { question: "einen Parkplatz", answer: "a parking lot/a parking space" },
      { question: "eine App", answer: "an app" },
      { question: "Lernen", answer: "learning" },
      { question: "die Gitarre", answer: "the guitar" },
      { question: "das Klavier", answer: "the piano" },
      { question: "das Instrument", answer: "the instrument" },
      { question: "das Interesse", answer: "the interest" },
      { question: "klug", answer: "clever, smart" },
      { question: "intelligent", answer: "intelligent" },
      { question: "die Bücherei", answer: "the library" },
      { question: "die Sprechstunde", answer: "the office hour" },
      { question: "erfahren", answer: "experienced" },
      { question: "kompliziert", answer: "complicated" },
      { question: "hart", answer: "hard, tough" },
      { question: "kapieren", answer: "to get, to understand" },
      { question: "die Prüfungen", answer: "the exam, the test" },
      { question: "die Prüferin", answer: "the examiner (female)" },
      { question: "die Einführung", answer: "the introduction" },
      { question: "die Disziplin", answer: "the discipline" },
      { question: "das Stipendium", answer: "the scholarship" },
      { question: "Ratschläge geben", answer: "give advice" },
      { question: "der Ratschlag", answer: "the advice" },
      { question: "bieten", answer: "to offer" },
      { question: "das Feedback", answer: "the feedback" },
      { question: "der Trick", answer: "the trick" },
      { question: "der Zeitplan", answer: "the schedule, the timetable" },
      { question: "realistisch", answer: "realistic" },
      { question: "die Energie", answer: "the energy" },
      { question: "lassen", answer: "to leave" },
      { question: "der Berufsalltag", answer: "the everyday working life" },
      { question: "der Arbeitgeber", answer: "the employer" },
      { question: "die Vollzeit", answer: "the full-time" },
      { question: "freiberuflich", answer: "freelance" },
      { question: "stundenweise", answer: "by the hour" },
      { question: "der PC", answer: "the PC, computer" },
      { question: "die Autorin", answer: "the author (female)" },
      { question: "der Babysitter", answer: "the babysitter" },
      { question: "ausländisch", answer: "foreign" },
      { question: "die Konferenz", answer: "the conference" },
      { question: "der Workshop", answer: "the workshop" },
      { question: "zusammenarbeiten", answer: "to work together, to collaborate" },
      { question: "pensioniert", answer: "retired (pensioned)" },
      { question: "die Rente", answer: "the pension" },
      { question: "die Seniorin", answer: "the senior (female)" },
      { question: "übersetzen", answer: "to translate" },
      { question: "die Übersetzung", answer: "the translation" },
      { question: "neutral bleiben", answer: "to remain neutral" },
      { question: "kommunizieren", answer: "to communicate" },
      { question: "die Kommunikation", answer: "the communication" },
      { question: "anderen helfen", answer: "to help others" },
      { question: "die Aktion", answer: "the action" },
      { question: "starten", answer: "to start, to launch" },
      { question: "sorgen", answer: "to care, to provide for" },
      { question: "der Service", answer: "the service" },
      { question: "reparieren", answer: "to repair" },
      { question: "die Reparatur", answer: "the repair" },
      { question: "wegwerfen", answer: "to throw away" },
      { question: "gebraucht", answer: "used, second-hand" },
      { question: "eine Präsentation halten", answer: "to give a presentation" },
      { question: "der Hauptteil", answer: "the main part" },
      { question: "der Inhalt", answer: "the content, matter" },
      { question: "der Punkt", answer: "the point" },
      { question: "der Schluss", answer: "the conclusion, end" },
      { question: "flüssig", answer: "fluent" },
      { question: "die Zuhörerin", answer: "the listener (female)" },
      { question: "das Standesamt", answer: "the registry office" },
      { question: "das Forum", answer: "the forum" },
      { question: "die Mailbox", answer: "the mailbox" },
      { question: "existieren", answer: "to exist" },
      { question: "putzen", answer: "to clean" },
      { question: "spülen", answer: "to rinse, to wash (dishes)" },
      { question: "fett", answer: "fat, oily, greasy" },
      { question: "die Qualität", answer: "the quality" },
      { question: "der Katalog", answer: "the catalog" },
      { question: "der Prospekt", answer: "the brochure" },
      { question: "das Herz", answer: "the heart" },
      { question: "die Figur", answer: "the figure, shape" },
      { question: "das Mineralwasser", answer: "the mineral water" },
      { question: "die Zitrone", answer: "the lemon" },
      { question: "die Portion", answer: "the portion" },
      { question: "tagsüber", answer: "during the day" },
      { question: "die Mitternacht", answer: "the midnight" },
      { question: "der Wald", answer: "the forest" },
      { question: "notwendig", answer: "necessary" },
      { question: "prima", answer: "great, excellent" },
      { question: "sowieso", answer: "anyway, in any case" },
      { question: "übrigens", answer: "by the way" },
      { question: "den Stoff", answer: "the material" },
      { question: "einen Ratschlag", answer: "a piece of advice" },
      { question: "Sport machen", answer: "to do sports " },
      { question: "bewegen", answer: "to move " },
      { question: "Kajak", answer: "the kayak " },
      { question: "Kitesurfen", answer: "the kitesurfing " },
      { question: "surfen", answer: "to surf " },
      { question: "tauchen", answer: "to dive (under water)" },
      { question: "langlaufen", answer: "cross country skiing" },
      { question: "Volleyball spielen", answer: "to play volleyball " },
      { question: "das Tor", answer: "the goal " },
      { question: "werfen", answer: "to throw " },
      { question: "mitspielen", answer: "play along" },
      { question: "das Rad", answer: "the bike" },
      { question: "die Radtour", answer: "the bike tour " },
      { question: "Yoga machen", answer: "to do yoga" },
      { question: "Kletterer", answer: "the climber (male)" },
      { question: "Kletterin", answer: "the climber (female)" },
      { question: "Gesundheit", answer: "the health" },
      { question: "entspannen (sich)", answer: "to relax (oneself)" },
      { question: "Fußballschuh", answer: "the soccer shoe" },
      { question: "Helm", answer: "the helmet" },
      { question: "Matte", answer: "the mat" },
      { question: "Mountainbike", answer: "the mountain bike" },
      { question: "das Surfbrett", answer: "the surfboard" },
      { question: "die Taucherbrille", answer: "the diving goggles" },
      { question: "die Mannschaft", answer: "the team" },
      { question: "der Fanartikel", answer: "the fan article" },
      { question: "treu", answer: "loyal" },
      { question: "benehmen (sich)", answer: "to behave (oneself) " },
      { question: "sympathisch", answer: "likable " },
      { question: "großartig", answer: "great " },
      { question: "genial", answer: "brilliant " },
      { question: "unglaublich", answer: "unbelievable" },
      { question: "die Hoffnung", answer: "the hope" },
      { question: "bestimmt", answer: "certainly" },
      { question: "Vorschläge machen", answer: "to make suggestions" },
      { question: "Was denkst du, sollen wir...?", answer: "What do you think, should we...?" },
      { question: "Wir könnten", answer: "We could" },
      { question: "einverstanden sein", answer: "to agree" },
      { question: "passen", answer: "to fit/suit" },
      { question: "unterwegs in D-A-CH", answer: "on the way in Germany, Austria, Switzerland" },
      { question: "die Anreise", answer: "the arrival" },
      { question: "der Einwohner", answer: "the resident (male)" },
      { question: "die Einwohnerin", answer: "the resident (female)" },
      { question: "kulturell", answer: "cultural" },
      { question: "das Gasthaus", answer: "the guesthouse" },
      { question: "hinunter", answer: "down" },
      { question: "der Nationalpark", answer: "the national park" },
      { question: "die Temperatur", answer: "the temperature" },
      { question: "stark", answer: "strong" },
      { question: "trocken", answer: "dry" },
      { question: "deshalb", answer: "therefore" },
      { question: "trotzdem", answer: "in spite of" },
      { question: "das Material", answer: "the material" },
      { question: "zurück geben", answer: "to give back" },
      { question: "der Kanton", answer: "the canton" },
      { question: "der Cousin", answer: "the cousin (male)" },
      { question: "die Cousine", answer: "the cousin (female)" },
      { question: "die Sendung", answer: "the broadcast" },
      { question: "eine Antwort geben", answer: "to give an answer" },
      { question: "der Hinweis", answer: "the hint" },
      { question: "übermorgen", answer: "the day after tomorrow" },
      { question: "neulich", answer: "recently" },
      { question: "einen Helm", answer: "a helmet" },
      { question: "tragen", answer: "to wear" },
      { question: "entspannen", answer: "to relax" },
      { question: "im Winter", answer: "in winter" },
      { question: "in den Bergen", answer: "in the mountains" },
      { question: "klettern", answer: "to climb" },
      { question: "ein Spiel", answer: "a game" }
    ],
    2: [
      { question: "Blume", answer: "flower" },
      { question: "Gras", answer: "grass" },
      { question: "Wald", answer: "forest" }
    ]
    // ...add more Kapitel as needed
  }
};
